### ISSUE TITLE
Full screen Video Cropped

### ISSUE THREAD

**Issue by ardynugraha** [itsnubix/react-native-video-controls#100]
When enter full screen video is cropped. How can the video is playing but in full screen without cropped some of video content?

Anyone can help?

**Comment by kylemilloy** [comment]
What's the value of your resizeMode prop? I'm guessing you're using cover which is why it's cropping. you can double tap the video to change the cropping.

**Comment by kylemilloy** [comment]
Closing for now....

**Comment by ardynugraha** [comment]
I'm not using resizeMode but video still cropped when enter fullscreen.
Here's my code:

`<VideoPlayer
style={{ backgroundColor: '#FFFFFF' }}
disableBack={true}
seekColor={'#F91A12'}
source={{ uri: this.props.data.attachment }}
navigator={this.props.navigator}
onEnterFullscreen={() => this.setState({ isFullscreen: true })}
onExitFullscreen={() => this.setState({ isFullscreen: false })}
/>`

**Comment by kylemilloy** [comment]
Please see the details on this ticket:

https://github.com/itsnubix/react-native-video-controls/issues/85

**Comment by kylemilloy** [comment]
The fullscreen prop just changes the resizeMode. You'll need to set it so the container goes fullscreen or perhaps better yet loads a new view with just the video controller in it.
