### ISSUE TITLE
Timer sometimes wraps to second line

### ISSUE THREAD

**Issue by hscheckenbacher-ambifi** [itsnubix/react-native-video-controls#103]
I have noticed that the timer sometimes wraps to the second line, pushing the pause button up. It's a minor issue but a little bit annoying when you see it jumping around with the controls up.

**Comment by kylemilloy** [comment]
How long are the videos that you're playing? What numbers are shown? I'm guessing it runs out of space in the view and wraps...something like 88:88 perhaps...

**Comment by hscheckenbacher-ambifi** [comment]
The text component is hardwired to 80 width, we adjusted it to 100 and it works perfectly. Probably just use a flex row layout down there, would do the trick. Thanks for getting back to me!

And to actually answer the question, it's -00:46 for example that wraps the 6 to the new line and then it jumps back for -00:45 ... this happens intermittently.
