### ISSUE TITLE
Stop animations on componentWillUnmount

### ISSUE THREAD

**Issue by EstebanBP** [itsnubix/react-native-video-controls#104]
When component is unmounted it does not stop animations I think.
What is happening now: 
- User clicks a button to show a video
- Navigator push a route with my component to show the video (which has VideoPlayer)
- onError prop is passed to the component so if video can not be played (youtube video, not .mp4, ... ), alert message is shown to the user and navigate back (VideoPlayer unmounts)
- Everything works ok but InteractionManager.runAfterInteractions(callback) will not work anymore in any component.

I think animations are not stopped safely on ComponentWillUnmount. Am I right?

VideoComponent
```
import React, { Component } from 'react';
import VideoPlayer from 'react-native-video-controls';

class CustomVideoPlayer extends Component {
  constructor(props) {
    super(props);
    this.state = {};
    this.onError = this.onError.bind(this);
  }

  onError() {
    // show some alert to the user 'video cannot be played' ... 
    // going back on my navigator (navigator.pop)
    this.props.navigator.pop();
  }

  render() {
    return (
        <VideoPlayer
          source={{ uri: this.props.videoLink }}
          paused={false}
          controlTimeout={15000} // hide controls after ms of inactivity.
          seekColor="#FFF" // fill/handle colour of the seekbar
          onBack={() => this.props.navigator.pop()} // Function fired when back button is pressed.
          onError={this.onError}
        />
    );
  }
}
```
In any other component
```
InteractionManager.runAfterInteractions(() => { 
// This code will never be executed anymore
})
```

"react": "^16.3.1"
"react-native": "^0.55.4"
"react-native-video-controls": "^2.2.1"
https://facebook.github.io/react-native/docs/interactionmanager

**Comment by EstebanBP** [comment]
Workaround: 
VideoComponent
<pre><code>
import React, { Component } from 'react';
import VideoPlayer from 'react-native-video-controls';

class CustomVideoPlayer extends Component {
  constructor(props) {
    super(props);
    this.state = {};
    this.onError = this.onError.bind(this);
  }

  onError() {
     <b>this.videoPlayer._onError();</b> //default _onError.
    // show some alert to the user 'video cannot be played' ... 
    // going back on my navigator (navigator.pop)
    this.props.navigator.pop();
  }

  render() {
    return (
        <VideoPlayer
          {<b> ref={r => (this.videoPlayer = r)}</b>
          source={{ uri: this.props.videoLink }}
          paused={false}
          controlTimeout={15000} // hide controls after ms of inactivity.
          seekColor="#FFF" // fill/handle colour of the seekbar
          onBack={() => this.props.navigator.pop()} // Function fired when back button is pressed.
          onError={this.onError}
        />
    );
  }
}
</code></pre>

**Comment by kylemilloy** [comment]
Please feel free to submit a pull request :)
