### ISSUE TITLE
Video play under video Unavailable notification

### ISSUE THREAD

**Issue by hungdev** [itsnubix/react-native-video-controls#105]
Hi guys.
the first time, I choose server 1, video play fine. when I choose to server 2 ( setState source video and link video error ), the video says error: Video Unavailable.
After that, I select sever 1 again, video plays under notification "Video Unavailable".
Please tell me how do I remove "video Unavailable" notification?
![un](https://user-images.githubusercontent.com/12009276/42726641-f2bbc5a8-87c1-11e8-8200-dfae603c89d2.gif)

**Comment by hungdev** [comment]
@kylemilloy thank you so much. 
I have read a lot of issues, and see your comment a lot. you are nice.
Thank your contribution to the community.
I love you so much.

**Comment by kylemilloy** [comment]
Haha, no problem bud. Happy to help.

**Comment by sokratisvs** [comment]
@kylemilloy I have the error { 1077, what:1 }, where can i find a file with the listing of different code errors?

**Comment by kylemilloy** [comment]
Please open another ticket.

**Comment by Spunnator** [comment]
In my App, the react-native-video doesn't show the video. I print onLoad callback and it returns this payload with some videos:
{"canPlayFastForward": true, "canPlayReverse": true, "canPlaySlowForward": true, "canPlaySlowReverse": true, "canStepBackward": true, "canStepForward": true, "currentTime": 0, "duration": 20.053, "naturalSize": {"height": 0, "orientation": "portrait", "width": 0}}

height and widht props are 0, why?

@kylemilloy Any solutions?

**Comment by 520hxw** [comment]
> 运行没问题啊 @kylemilloy太感谢了。 我读了很多问题，也看到了很多你的评论。你人真好。 感谢您对社区的贡献。 我真的很爱你。



> It's run oke. @kylemilloy thank you so much. I have read a lot of issues, and see your comment a lot. you are nice. Thank your contribution to the community. I love you so much.

I met the same problem as you, can you tell me how you solved this problem？
 I choose to server 1 ( setState source video and link video error ), the video says error: Video Unavailable.
After that, I select sever 2 , video plays under notification "Video Unavailable".

**Comment by mmp-star** [comment]
> It's run oke. @kylemilloy thank you so much. I have read a lot of issues, and see your comment a lot. you are nice. Thank your contribution to the community. I love you so much.

I met the same problem as you, can you tell me how you solved this problem？
I choose to server 1 ( setState source video and link video error ), the video says error: Video Unavailable.
After that, I select sever 2 , video plays under notification "Video Unavailable".
