### ISSUE TITLE
【Bug】When I enter this video time and again，the video crash

### ISSUE THREAD

**Issue by youngjuning** [itsnubix/react-native-video-controls#106]
![image](https://user-images.githubusercontent.com/13204332/42859480-ae287d84-8a85-11e8-9dcb-7936d669be01.png)

**Comment by youngjuning** [comment]
no error on here，and  I just hide the Modal,

```js
<Modal visible={this.state.VideoModalVisible} transparent onRequestClose={() => {}}>
          <VideoPlayer
            ref={(c) => { this.player = c }}
            source={{uri: this.state.videoPath}}
            style={[styles.backgroundVideo]}
            disableVolume
            paused={this.state.paused}
            onError={(e) => {
              console.log('播放错误', e)
            }}
            onEnd={() => {
              this.player.seekTo(0)
              this.setState({
                paused: true,
              })
            }}
            onBack={() => {
              this.setState({
                paused: false,
                videoPath: '',
                VideoModalVisible: false,
              })
            }}
          />
        </Modal>
```

**Comment by kylemilloy** [comment]
If it's not popping an error then there's no crash and is likely unrelated to the player. Check the URL you're feeding into the app on render with `{ console.log(this.state.videoPath) }`. What is that URL? Test to make sure it works in other players.

**Comment by kylemilloy** [comment]
Written a way that should be easier to translate:

**Comment by kylemilloy** [comment]
Written in a way that's easier to translate:

**Comment by youngjuning** [comment]
当我第一次进入打开 `Modal` 的时候，视频可以播放。但是第二次或者第三次打开 `Modal` 时，就出现了这个问题

**Comment by youngjuning** [comment]
![image](https://user-images.githubusercontent.com/13204332/42860075-2568af2a-8a88-11e8-8519-317259ec92a7.png)

And the video has no problem

**Comment by kylemilloy** [comment]
I see...I notice in `onBack` you're clearing the `videoPath`...what is the process you use for loading new videos the second or third time?

**Comment by youngjuning** [comment]
![image](https://user-images.githubusercontent.com/13204332/42860406-e47666be-8a88-11e8-86f1-bc6ada4dc671.png)

次数是随机的，有时候是在第四次...

**Comment by youngjuning** [comment]
就算不清空，点击其他视频消息，也会被替换掉的

**Comment by kylemilloy** [comment]
Random, eh? Weird...

Lemme think about this for a bit...can you share more of your code so I can see how things are interconnected?

**Comment by youngjuning** [comment]
如果我把这个组件作为一个页面而不是写在 `Modal` 里边，是不是就不会出现这个问题了？

**Comment by youngjuning** [comment]
这段代码是在一个页面中的，你可以使用 `Button` 来控制

```js
...
import {
  View,
  Platform,
  Modal,
  StyleSheet,
} from 'react-native'
...
<Button onPress = {() => { this.setState({ videoPath: 'An Video',VideoModalVisible:true }) }}>
<Modal visible={this.state.VideoModalVisible} transparent onRequestClose={() => {}}>
  <VideoPlayer
    ref={(c) => { this.player = c }}
    source={{uri: this.state.videoPath}}
    style={[styles.backgroundVideo]}
    disableVolume
    paused={this.state.paused}
    onError={(e) => {
      console.log('播放错误', e)
    }}
    onEnd={() => {
      this.player.seekTo(0)
      this.setState({
        paused: true,
      })
    }}
    onBack={() => {
      this.setState({
        paused: false,
        VideoModalVisible: false,
      })
      this.props.navigation.goBack('VideoPlayer')
    }}
  />
</Modal>
...
backgroundVideo: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
```

**Comment by kylemilloy** [comment]
Thank you for posting your code.

I've never used the video player in a `Modal` so I can't say for sure if you're encountering a problem because of this. You may have better results using the player as a page:


```js
// <Modal>
  <VideoPlayer />
// </Modal>
```

I was going to suggest changing your `onBack` method to not change `videoPath` to an empty string but I see you've already done that...

Is it possible that `state.paused` is in the wrong value after a couple times?

**Comment by youngjuning** [comment]
如果删了 `state.paused`，还是会有这个问题的。I would like to use `<VideoPlayer />` as a page. Thank you very much.

**Comment by kylemilloy** [comment]
You don't have to delete state.paused...but set it to true when you click the button:

```js
<Button onPress = {() => { 
  this.setState({ 
    videoPath: 'An Video',
    VideoModalVisible:true,
    paused: false
  }) 
}}>
```
