### ISSUE TITLE
[Android] video plays the first time and afterwards video unavailable

### ISSUE THREAD

**Issue by sokratisvs** [itsnubix/react-native-video-controls#108]
@kylemilloy In Android I can play a video (m4v/mp42/isom) once but after pressing play to play again, it shows the following error: { error: { extra: -1007, what: 1 } }, so according to https://developer.android.com/reference/android/media/MediaPlayer#MEDIA_ERROR_IO

```
MEDIA_ERROR_MALFORMED
added in API level 17
public static final int MEDIA_ERROR_MALFORMED
Bitstream is not conforming to the related coding standard or file spec.

Constant Value: -1007 (0xfffffc11)
```
So the codec used in this video is not conforming to the related coding standard, then how can it play the first time?

**Comment by kylemilloy** [comment]
Can you show me an example of your implementation as well as the URL for the video?

**Comment by kylemilloy** [comment]
And are you using a website URL or are you requiring the URL as it's a part of your app?

**Comment by sokratisvs** [comment]
I'm using dynamic link through web service in ```this.state.video```, here is the implementation of Video in my component:

```
 componentDidUpdate = (prevProps, prevState) => {
        if (this.state.video && this.state.ended)
            this._videoRef.seekTo(0);
    }

  <View style={{ display: 'flex', justifyContent: 'center' }}>
                        <VideoPlayer
                            source={{ uri: `${this.state.video}`, mainVer: 1, patchVer: 0 }}
                            style={{ width: (width > 500) ? width - 100 : width - 10, height: (width > 500) ? width / 2 : 200 }}
                            ref={(ref) => this._videoRef = ref}
                            setControls={true}
                            repeat={false}
                            resizeMode="cover"
                            paused={true}
                            navigator={this.props.navigator}
                            disableBack={true}
                            // onEnd={() => this.playNext()}
                            onEnd={() => this.setState({ paused: true, ended: true }) }
                            onError={
                                err => console.log(err)
                            }
                        />
                    </View>
```

**Comment by kylemilloy** [comment]
What's the reason you're using expansion files?

**Comment by sokratisvs** [comment]
@kylemilloy you mean URLs that change dynamically? It's the way that we are using the service..here is a sample of the response URL
`https://xyz.abc.gr:443/web/abc/def?p_p_mode=view&p_p_cacheability=cacheLevelPage&some_other _parameters`

**Comment by kylemilloy** [comment]
Hey...any update on this?
