### ISSUE TITLE
Can't back when video Url error on IOS

### ISSUE THREAD

**Issue by hungdev** [itsnubix/react-native-video-controls#109]
With Android, it works perfectly.  But on Ios, with correct video url it can back. If the video url error, it can not back. Please look at the gif.
![ev2](https://user-images.githubusercontent.com/12009276/43032618-babd71c8-8ce5-11e8-9c39-aba0479bcf92.gif)

My code:
```
          <VideoPlayer
            source={{ uri: movieSelected }}
            controlTimeout={10000}
            navigator={this.props.navigation}
            onEnterFullscreen={Orientation.lockToLandscape}
            onExitFullscreen={Orientation.lockToPortrait}
            onError={(err) => this.showMessageBar()}
            onBack={() => this.onBackMovie()}
          />
```

```
  onBackMovie() {
    this.props.navigation.goBack()
    Orientation.lockToPortrait()
  }
```

thank you.

**Comment by hungdev** [comment]
@kylemilloy could you help me?

**Comment by hungdev** [comment]
i found the issue. it conflicts with `react-native-flash-message` lib.

**Comment by hungdev** [comment]
It's not because of conflicts with react-native-flash-message, but because the onError function causes an error.

**Comment by thatjuan** [comment]
How did you fix this?

**Comment by hungdev** [comment]
@thatjuan with ios: remove onError props. After that, you will get an error cant hide notification. You will need this code in the pull request https://github.com/itsnubix/react-native-video-controls/pull/111

**Comment by thatjuan** [comment]
nicely done, thanks!

**Comment by kylemilloy** [comment]
Sorry all...been away for a bit..I'll take a peek at your changes and merge them into the repo.

**Comment by zero1108** [comment]
what kind of error did the onError function caused?
