### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ithieund** [itsnubix/react-native-video-controls#11]
I tried a fresh install but no luck.
I showed an err

<img width="173" alt="screenshot at dec 08 16-58-36" src="https://cloud.githubusercontent.com/assets/4217195/21005488/99570aac-bd67-11e6-8a9c-ca7245f6d747.png">

My react-native version is 0.37.0
Can you please help?

**Comment by kylemilloy** [comment]
Can you share your code?

**Comment by kylemilloy** [comment]
Be sure to follow the steps for Android installation on the react-native-video page here:
https://github.com/react-native-community/react-native-video#android

Specifically see this section for RN > v29
https://github.com/react-native-community/react-native-video#note-in-react-native--0290-you-have-to-edit-mainapplicationjava

After this is done, restart the simulator with run-android again.

**Comment by ithieund** [comment]
@kylemilloy,
It worked.

Thanks for your help.

**Comment by kylemilloy** [comment]
@ithieund excellent. Let me know if you need anymore help.
