### ISSUE TITLE
PlayPause, volume hanlde missing on real device

### ISSUE THREAD

**Issue by klooperator** [itsnubix/react-native-video-controls#110]
When debugging ( running on V8) I see all controls normally. But when I disconnect from remote debugger I lose PlayPause button and volume handler ( I disable most of the rest controls). Seekbar and seek handle ( circle) is showing normally. Volume bar is present, but without volume icon.

Env conf:
Android 8,
gradle: 3.1.2
buildToolsVersion = "27.0.3"
    minSdkVersion = 16
    compileSdkVersion = 27
    targetSdkVersion = 27
    supportLibVersion = "27.1.0" 
"react-native": "0.56.0",
"react": "16.4.1",
"react-native-video": "^2.3.0",
"react-native-video-controls": "^2.2.3",

**Comment by AngelsProjects** [comment]
I have the same error is there a solution?

**Comment by inpendio** [comment]
I did solve it, but its not nice :)
I just copied their code and assets to my project root... Yeah, dumb, but quick :)
