### ISSUE TITLE
Android ExoPlayer video/poster display issue

### ISSUE THREAD

**Issue by pqminh** [itsnubix/react-native-video-controls#115]
Current behavior
I don't know why my video play wrong position. Video is playing at the top and poster or something display at bottom like picture below.

Expected behavior
Video play fullscreen.

Platform
Which player are you experiencing the problem on:

Android ExoPlayer
"react-native-video": "^3.2.0",
"react-native": "^0.47.2",
![1536757514084](https://user-images.githubusercontent.com/13993984/45427791-f5018780-b6c9-11e8-8499-e3eb203d69ab.JPEG)

**Comment by kylemilloy** [comment]
This is likely a style issue...please reopen and post some of your code so I can help.
