### ISSUE TITLE
Toggle fullscreen button 

### ISSUE THREAD

**Issue by LucasMMota** [itsnubix/react-native-video-controls#116]
I'm using the video player with a modal and I'd like to toggle fullscreen button.

For example, when my modal open with the video inside, I want the fullscreen button indicating to close fullscreen(-><-). But the atual state it indicates to open fullscreen(<-->). This can confuse the user.

The image shows the atual button state, I want the opposite on this case.
I would like to add a property to toggle this button.
![screenshot_20180928-170037](https://user-images.githubusercontent.com/13151948/46231419-3c327e00-c342-11e8-9b4c-8128b496996e.png)

Do you know if it's possible to do that on atual version of the react-native-video-controls? Or think it could be done?

Bests,
Lucas Fonseca

**Comment by redmond-ingenuity** [comment]
i think you can do it by using the event onEnterFullscreen={this.setState({ fullscreen: true})} then use the disableFullscreen={this.state.fullscreen}

**Comment by kylemilloy** [comment]
Should be doable via the onEnterFullscreen/onExitFullscreen events. when you toggle the button you can add some callbacks in there to handle this.

**Comment by pawani-K** [comment]
i Tried with call backs  1st it shows exit full screen button onclick shows full screen button then if i click full screen it shows full video......
 But **starting it should show full screen button**.../////Any HELP!!!!!!!
And Video doesnt plays in IOS    "it shows video unavailable"
https://user-images.githubusercontent.com/118712751/215453504-a3ada4eb-7aa9-4ba1-bfe0-c05513aa7fb8.png
<VideoPlayer
source={{ uri: videoUrl }}
seekColor="white"
disableVolume={true}
disableBack={true}
showOnStart={true}
fullScreen={isFullScreenMode}
resizeMode={'cover'}
ignoreSilentSwitch="ignore"
fullscreenOrientation="landscape"
// toggleResizeModeOnFullscreen={false}
onEnterFullscreen={() => setIsFullScreenMode(true)}
onExitFullscreen={() => setIsFullScreenMode(false)}
videoStyle={{ backgroundColor: "#f8f8ff" }} 
> />
