### ISSUE TITLE
Top controls don't work on iPhoneX in portrait mode

### ISSUE THREAD

**Issue by akandaurov** [itsnubix/react-native-video-controls#118]
Top controls: back, volume, zoom don't work on iPhoneX in portrait mode
Control styles are hardcoded and can't be customized, e.g.
styles.controls.topControlGroup: {
    ...
    margin: 12
    marginBottom: 18
}

**Comment by fendorio** [comment]
Could you wrap your video in React Native's [SafeAreaView](https://facebook.github.io/react-native/docs/safeareaview)?

**Comment by akandaurov** [comment]
I'll try, but the video won't take full screen in this case which may not look good

**Comment by akandaurov** [comment]
SafeAreaView does additional padding in the bottom and does paddings in landscape orientation as well which I don't need at all. Also padding solution is not good. I did a fork with customizable top and bottom control group styles and then adjusted top margin for top group controls in my code when run on iPhoneX and in portrait orientation.

**Comment by kylemilloy** [comment]
This is fixed in way back in 2.3 as part of a fix to resolve https://github.com/itsnubix/react-native-video-controls/issues/144
