### ISSUE TITLE
Crashes with New version of react-native-video

### ISSUE THREAD

**Issue by mondoul** [itsnubix/react-native-video-controls#12]
Hi
with the newer version of React, react-native-video had to be updated to support onProgress and onLoad, but the controls are no longer working and the app crashes when trying to render. 
To reproduce it, juste replace your dependency 
`"react-native-video": "^0.9.0"` to 
`"react-native-video": ""git+https://github.com/react-native-community/react-native-video.git#master""`

Thanks for your help

**Comment by kylemilloy** [comment]
Thanks for reporting this. I'll take a look over the weekend.

**Comment by mondoul** [comment]
FYI, I stop having the issue if I remove `playInBackground={ this.opts.playInBackground }` from the `render()` method. It seems to be related to [this issue](https://github.com/react-native-community/react-native-video/issues/418)

**Comment by kylemilloy** [comment]
I can't repeat this issue but I'm going to start using the git repo for the react-native-video source for now as there's a couple bugs that RN 39 have created.
