### ISSUE TITLE
Disable Loader or Allow Icon & Styling

### ISSUE THREAD

**Issue by FullstackJack** [itsnubix/react-native-video-controls#120]
I want to use these controls in a portrait view news feed, unfortunately the loader takes over the whole screen and the rest of the page can't be seen.

I looked through the source but unfortunately, the styling props are extremely limited here. We should be able to pass a `controlStyle` prop that merges with the one you create at the bottom of the file. I really need to override a ton of styles here. Also I want to use my own icons.

Something like this...

```
const styles = {
  loader: {
    backgroundColor: 'white',
    position: 'relative',
    top: null,
    bottom:  null,
    right: null,
    left: null,
    width: Dimensions.get('window').width,
    height: Dimensions.get('window).width * 9 / 16,
  }
}

...
render() {
  return (
    <Video
      source={...}
      controlStyle={styles}
    />
  )
}
```

**Comment by alburdette619** [comment]
This whole project is lacking in a lot of possible customizations. Idk if that is by design. I need custom icons, custom positioning, etc. This library has been around for so long it makes me wonder if the design is locked on purpose.

**Comment by kylemilloy** [comment]
It's definitely an opinionated component. 

We're working on making that better for v3 by stepping away from doing things that we *needed* it to do and going after what we feel the community will want with some defaults that should be helpful...stay tuned over the next month as we roll this out.
