### ISSUE TITLE
videoStyle and style not updated on state change

### ISSUE THREAD

**Issue by nevaehph** [itsnubix/react-native-video-controls#122]
I am attempting to scale the `<VideoPlayer>` height to be based on the video's natural sizes using onLoad. My codes for the VideoPlayer are as follows:

```
<VideoPlayer
    source={{ uri: "http://techslides.com/demos/sample-videos/small.mp4" }}
    disableBack={true}

    style={{
        width: this.state.screenWidth,
        height: this.state.heightScaled
    }}
    videoStyle={{
        width: this.state.screenWidth,
        height: this.state.heightScaled
    }}

    paused={this.state.videoPaused}

    onLoad={this.scaleVideo}
/>
```
With the `scaleVideo` as follows:
```
scaleVideo = response => {
        const newHeight = response.naturalSize.height * (this.state.screenWidth / response.naturalSize.width);        
        this.setState({heightScaled: newHeight});
    }
```
`this.scaleVideo` was called but the video player's height was not updated to the new state value `heightScaled`. I tried it using `react-native-video` alone and the following codes worked. Am I missing something here? What is the solution to this problem?

**Comment by nevaehph** [comment]
After some exploring in VideoPlayer.js, I have found that comparing the style properties with the ones from `this.styles` and updating them if different, similar to how the the `paused` state is handled at `componentWillReceiveProps`, will resolve this issue. The codes I have edited are as follows:

```
componentWillReceiveProps(nextProps) {
        if (this.state.paused !== nextProps.paused ) {
            this.setState({
                paused: nextProps.paused
            })
        }

        if(this.styles.videoStyle !== nextProps.videoStyle){
            this.styles.videoStyle = nextProps.videoStyle;
        }
        if(this.styles.containerStyle !== nextProps.style){
            this.styles.containerStyle = nextProps.style;
        }
}
```

**Comment by t-hughes** [comment]
#166

**Comment by kylemilloy** [comment]
Resolved in https://github.com/itsnubix/react-native-video-controls/pull/166
