### ISSUE TITLE
Shrinking Top Control

### ISSUE THREAD

**Issue by nic-thomson** [itsnubix/react-native-video-controls#124]
Heres a overview of my basic setup
`react native:0.55.4`  
` react-native-navigation:2.1.3`
` react-native-video-controls:2.2.3 `

Im experiencing a problem where the top control group, gets progressively smaller each time it's displayed.  Changing the volume via the slider will fix the height of the volume control.  
The window is displayed on a react-native-navigation[v2] stack, changing this to a modal had no effect.  I've attached  couple of images to illustrate the point.  (with changed background colours) 

on original  display:
![simulator screen shot - iphone xr - 2018-11-16 at 11 15 08](https://user-images.githubusercontent.com/5494449/48633280-03517580-e991-11e8-94a5-b73251b4b653.png)

after several display/hide controls, the top bar has shrunk
![simulator screen shot - iphone xr - 2018-11-16 at 11 15 20](https://user-images.githubusercontent.com/5494449/48633378-309e2380-e991-11e8-95ea-33848a32fe67.png)

This seems to be an iOS problem only, android version does not have the same problem.
Has anyone seen anything like this ? Any ideas how i could fix this ?

**Comment by clementbmn** [comment]
Hi, my solution has been to remove the top animations of the top margin, letting the opacity in `hideControlAnimation`
Now it is :

`hideControlAnimation() {
        Animated.parallel([
            Animated.timing(
                this.animations.topControl.opacity,
                { toValue: 0 }
            ),
            Animated.timing(
                this.animations.bottomControl.opacity,
                { toValue: 0 }
            ),
        ]).start();
    }`

**Comment by nic-thomson** [comment]
We'e now upgraded react-native to 0.59.3 and the problem is resolved.  It seems this was a an issue in react-native itself.
