### ISSUE TITLE
Top & Bottom control container show/hide props

### ISSUE THREAD

**Issue by webmasterdragon** [itsnubix/react-native-video-controls#127]
If you can add Top/Bottom control container show/hide props would be great.
https://github.com/itsnubix/react-native-video-controls/blob/f41a624f3b758736333717b657e7bd91b4866137/VideoPlayer.js#L1131

**Comment by webmasterdragon** [comment]
Also top/bottom control container style props.

**Comment by kylemilloy** [comment]
Won't release this for v2 as it'll be large of an impact....but keep an on the dev branch as we're looking at rebuilding this the component.
