### ISSUE TITLE
Progress slider dragging in RTL

### ISSUE THREAD

**Issue by cybercoder** [itsnubix/react-native-video-controls#130]
When the android APP is in RTL mode the progress slider has not correct behavior.
And i don't know how can make a component LTR when the whole of APP is in RTL mode.

**Comment by kylemilloy** [comment]
What's the expected behaviour in RTL? Fill bar moves from RTL with the text direction?

**Comment by cybercoder** [comment]
In LTR, when drag slider from left to right video progress will forward, In RTL should be reverse.

**Comment by kylemilloy** [comment]
Fork the project...then look at modifying the `calculateSeekerPosition` and `calculateTimeFromSeekerPosition` function inside VideoPlayer.js.

Right now it calculates its position along a track LTR so if you were to get the inverse of these calculations with someone like the following:
```
calculateSeekerPosition() {
    const percent = this.state.currentTime / this.state.duration;
    return this.player.seekerWidth * (1 - percent);
}

calculateTimeFromSeekerPosition() {
    const percent = this.state.seekerPosition / this.player.seekerWidth;
    return this.state.duration * ( 1 - percent);
}
```

**Comment by cybercoder** [comment]
```javascript
            onPanResponderMove: ( evt, gestureState ) => {
                const position = this.state.seekerOffset - gestureState.dx;
                this.setSeekerPosition( position );
            },
```

**Comment by elbadrawy** [comment]
> Fork the project...then look at modifying the `calculateSeekerPosition` and `calculateTimeFromSeekerPosition` function inside VideoPlayer.js.
> 
> Right now it calculates its position along a track LTR so if you were to get the inverse of these calculations with something like the following:
> 
> ```js
> calculateSeekerPosition() {
>     const percent = this.state.currentTime / this.state.duration;
>     return this.player.seekerWidth * (1 - percent);
> }
> 
> calculateTimeFromSeekerPosition() {
>     const percent = this.state.seekerPosition / this.player.seekerWidth;
>     return this.state.duration * (1 - percent);
> }
> ```

this is not enough to support RTL
also must modifying `onPanResponderMove ` on `initSeekPanResponder` to be like this
> ```js
> onPanResponderMove: ( evt, gestureState ) => {  
>              let position;
>              if(I18nManager.isRTL){
>                    position = this.state.seekerOffset + (1 - gestureState.dx);
>               }else{
>                    position =  this.state.seekerOffset + gestureState.dx;
 >               }
 >              this.setSeekerPosition( position );
 >          },
> ```
and the same on function `initVolumePanResponder`
but to avoid changes in functions we can set style `flexDirection` of track container and volume container
to be `row-reverse` instead of` row` when `I18nManager.isRTL` is` true`

**Comment by kylemilloy** [comment]
I speak English and French...I don't have a lot of experience with RTL languages. For v3 we have localization on the roadmap for support. Will be looking for people to help with this when the time comes to implement it fully.

**Comment by sinafbd** [comment]
have problem in rtl here too
