### ISSUE TITLE
app permissions - bluetooth and microphone

### ISSUE THREAD

**Issue by Viswa-Vinod** [itsnubix/react-native-video-controls#135]
When my app, which includes the rnvideo-controls plugin is submitted to the apple store, I am sent an email that my app is requesting microphone and bluetooth permissions. This happens only in the screen where the rnvideo-contros is used. Does this lib seek and get these permissions? If so, how can I stop that?

**Comment by kylemilloy** [comment]
This package itself does not request those permissions but the [react-native-video](https://github.com/react-native-community/react-native-video) package might...I'd check in there.
