### ISSUE TITLE
How to disable auto play? and fulscreen

### ISSUE THREAD

**Issue by muhammadwfa** [itsnubix/react-native-video-controls#137]
I need to manual start the video and here I cant see any props for disabling auto play.
Also fullscreen does not work

**Comment by kylemilloy** [comment]
Please share your code. See the notes in other issues RE: fullscreen.

**Comment by vinilprabhu** [comment]
There is no option to dissable auto play, i want users to manually press play button to play the video

**Comment by kylemilloy** [comment]
Set paused to true.
