### ISSUE TITLE
Add typescript typings

### ISSUE THREAD

**Issue by slavikdenis** [itsnubix/react-native-video-controls#140]
It would be great if we could add simple typescript typings. Would you accept a PR? :)

**Comment by kylemilloy** [comment]
I would.

**Comment by slavikdenis** [comment]
@kylemilloy PR submitted :) https://github.com/itsnubix/react-native-video-controls/pull/141

**Comment by slavikdenis** [comment]
Any updates on the PR ? :)

**Comment by kylemilloy** [comment]
Sorry man -- been hectic...after review we're avoiding going full bore on TypeScript. Either it's all in TS or it's not in TS at all. We're going to instead look at `static defaultProps` and `static propTypes` class vars instead.
