### ISSUE TITLE
The back button is difficulty to be click on iphoneX

### ISSUE THREAD

**Issue by samuelltk** [itsnubix/react-native-video-controls#144]
The back button is difficulty to be click on iphoneX

**Comment by ds8k** [comment]
Try wrapping your video in a SafeAreaView

**Comment by kylemilloy** [comment]
Agreed. This came out before the iPhone X and the whole "notch" area of phones....working on a new version that should address this but will push out a small update to wrap controls in a safe area soon for v1.
