### ISSUE TITLE
Play/Pause button not working properly

### ISSUE THREAD

**Issue by muhammad-nauman** [itsnubix/react-native-video-controls#150]
This is the code:
```
<Video
       source={{uri: this.state.file}}
       style={{
             position: 'absolute',
             top: 0,
             left: 0,
             bottom: 0,
             right: 0,
        }}
       controls={true}
        resizeMode='contain'
       onBack={() => onClose(this.state.seconds)}
        ref={ ref => this.Ref = ref}
       paused={false}
/>
```

Video starts perfectly fine but play/pause button doesn't work. When I try to pause the video it pauses it for few milliseconds and then play it automatically. I didn't find any examples to know if it needs to be handled manually.

**Comment by muhammad-nauman** [comment]
Anyone care to comment?

**Comment by ds8k** [comment]
Could it be because you're setting `paused` to false?

**Comment by muhammad-nauman** [comment]
@ds8k no, I did it later. I used it without `paused` prop and it didn't work either

**Comment by Mifayo** [comment]
when it start are changing to fullsceen or rotate your phone ??

**Comment by muhammad-nauman** [comment]
@Mifayo it was happening on any orientation. 
Thanks all for your attention. I ended up removing it and went up with a custom implementation of player functionality.
