### ISSUE TITLE
Seekbar Issues

### ISSUE THREAD

**Issue by Appdevsoft** [itsnubix/react-native-video-controls#151]
I want to show time when I invoke the Seekbar.

**Comment by kylemilloy** [comment]
Closing for no detail....feel free to post with your codebase if you want some help and I'll reopen.

**Comment by babitakapoor112** [comment]
Hi,
I have an issue regarding the seek bar. Its progress is not moving completely. 

https://user-images.githubusercontent.com/45659052/114828467-905dba80-9de7-11eb-8d47-d8779719eaed.mp4
