### ISSUE TITLE
How to change a view of seek bar after moving from a fullscreen to a custom size of the video player ?

### ISSUE THREAD

**Issue by MaxKoldun** [itsnubix/react-native-video-controls#152]
Hi everybody, i have a problem, when i change a seeker position in a fullscreen mode it will unavailable if i change a size of the video player to smaller one, i'll show:
 
![photo_2019-09-23_20-30-48](https://user-images.githubusercontent.com/26070949/65448273-1d75a300-de41-11e9-8d3b-839c93f92c97.jpg)
![photo_2019-09-23_20-30-48 (2)](https://user-images.githubusercontent.com/26070949/65448275-1d75a300-de41-11e9-9cb7-49c9bd200f91.jpg)

on the second slide the seeker does not available for changing, how can i solve it ?

**Comment by kylemilloy** [comment]
Can you provide your code for this?

**Comment by MaxKoldun** [comment]
I've solved the problem
