### ISSUE TITLE
Changes video orientation

### ISSUE THREAD

**Issue by raphaelluiz128** [itsnubix/react-native-video-controls#155]
Is there any way we can click the fullscreen button and the video changes its orientation? such as vertical and horizontal?

**Comment by raphaelluiz128** [comment]
Guys, i used the transform and rotate in stylesheed, it's works. Thanks.

**Comment by laurent22** [comment]
For those looking for the answer, here's how to do it:

```js
<VideoPlayer
    videoStyle={{transform: [{ rotate: '90deg'}]}}
    ...
/>
```
