### ISSUE TITLE
Updated alternative/fork?

### ISSUE THREAD

**Issue by rafaismyname** [itsnubix/react-native-video-controls#158]
Seems like this project is, unfortunately, abandoned by the maintainers.
There are many open PRs that contributors have spent time on submitting that never got merged. 

Does anyone know about a great, well-maintained, alternative or updated fork to this?

**Comment by kylemilloy** [comment]
Hey -- sorry for the lack of maintenance here. We've been doing mostly native apps in Java/Swift for the last little bit but are moving back towards an RN project that will use this soon. At that time we'll overhaul this...I'll keep you posted and update this ticket once that's done.

**Comment by kylemilloy** [comment]
You can track development here: https://github.com/itsnubix/react-native-video-controls/tree/dev

Looking at overhauling this and allowing a lot more freedom in the player's chrome...removing a lot of opinionated functionality (for example; v1 assumes a user will open a new view to play the video) and providing a more customizable approach to the whole thing. Looking at overhauling this with a Control.js component that you can pass a function to on press. Also exposing the reference to the player a little more intuitively. 

I'm open to suggestions on how you think this should be enhanced.
