### ISSUE TITLE
IOS doesn't play sound if the phone is on silent mode 

### ISSUE THREAD

**Issue by miteshkotak** [itsnubix/react-native-video-controls#159]
Apple device doesn't play sound if the device is on silent mode.

**Comment by kylemilloy** [comment]
Sounds about right....can you gimme some more details for what you expect?

**Comment by miteshkotak** [comment]
The sound of the video doesn't work if the IOS device is on silent mode.
We need something like 
 ignoreSilentSwitch={"ignore"}
button which is present in react native video package

**Comment by kylemilloy** [comment]
If it’s available in the RNV package you can pass that prop to the videoplayer and it’ll forward it to video component child. 

On Nov 12, 2019, at 06:55, Mitesh Kotak <notifications@github.com> wrote:

﻿

The sound of the video doesn't work if the IOS device is on silent mode.

We need something like
ignoreSilentSwitch={"ignore"}
button which is present in react native video package
