### ISSUE TITLE
Subtitles picker?

### ISSUE THREAD

**Issue by ferrannp** [itsnubix/react-native-video-controls#160]
I like the native iOS controls but I cannot get ride of the resize button on the top left corner. That is why I was trying this library. However, I lose the ability to pick subtitles track in HLS video. Is there away to access such subtitles picker? Or to pass the selected track programatically?

**Comment by kylemilloy** [comment]
Not without a PR there isn't ;). Just controls here...no i18n or subtitles stuff. Sorry champ.
