### ISSUE TITLE
Support for touch to seek

### ISSUE THREAD

**Issue by Krypternite** [itsnubix/react-native-video-controls#161]
Thanks for the awesome library. Please please bring support for touch to seek soon. I am having a lot of issues with drag to seek.

I have my videos inside react-native-swiper and upon dragging the seekbar, the whole slide gets dragged. So it would really be useful if you could add touch to seek support. 
I have made an audio player for react-native-video using react-native-progress, may be that could help.

**Comment by kylemilloy** [comment]
There are a couple forks that use this but in our testing we found with the current controls layout that it was too easy to accidentally seek instead of play/pause the video.
