### ISSUE TITLE
Video does not plays 

### ISSUE THREAD

**Issue by gauravsbagul** [itsnubix/react-native-video-controls#163]
`<Video
				controls
				disableFullscreen
				disableBack
				showOnStart={true}
				source={{ uri: 'https://stemuli.blob.core.windows.net/stemuli/static/STEMuli_ShortCommercial.mp4' }}
				resizeMode="cover"
				paused={true}
				playInBackground={false}
				playWhenInactive={false}
				fullscreenOrientation="landscape"
				videoStyle={{ marginTop: StatusBar.currentHeight, margin: 10 }}
				onBuffer={e => onBuffer(e)}
				videoError={e => videoError(e)}
				onLoad={e => onLoad(e)}
				onEnd={e => onEnd(e)}
				onError={e => onError(e)}
			/>`
I am trying to stream video from web and ut gives me an error screen shot attached below, need help on it. 
![image](https://user-images.githubusercontent.com/25247251/69037875-b1618680-0a0e-11ea-93c4-d65927855a46.png)

**Comment by TalonHughes13** [comment]
I am getting the same issue on Android 7 in the emulator. It seems to work on my Pixel 4 running Android 10.

**Comment by TalonHughes13** [comment]
@gauravsbagul look at the issue on the react-native-video library: https://github.com/react-native-community/react-native-video/issues/1186

**Comment by gauravsbagul** [comment]
@TalonHughes13  thanks man, I am still facing the same issue.

**Comment by kylemilloy** [comment]
Closing, related to https://github.com/react-native-community/react-native-video
