### ISSUE TITLE
expose `onControlShow` and `onControlHide`

### ISSUE THREAD

**Issue by Crizzooo** [itsnubix/react-native-video-controls#164]
We are currently using `react-native-video-controls` and would like to add our own custom controls and information that should only be visible when the controls are visible.

Rather than add our own `onPress` and try to keep it in sync with the `controlTimeout`, it would be great to hook in to the library and know when the controls are shown and paused.

Proposal:

Inside `_toggleControls` add conditional calls to `this.props.onControlShow` and `this.props.onControlHide`

Thoughts?

If acceptable, I'll make a PR and update the `README`

**Comment by kylemilloy** [comment]
You can now utilize `onShowControls` and `onHideControls` events.

**Comment by Rotemy** [comment]
@kylemilloy Hi, thanks for the library.

The problem is that you are only taking the props on the constructor so if I want to use dynamic variables in the function I can't (without re-rendering the component).
