### ISSUE TITLE
Remove old lifecycle methods

### ISSUE THREAD

**Issue by KristineTrona** [itsnubix/react-native-video-controls#168]
From React 17.0 on ``componentWillReceiveProps `` and ``componentWillMount`` lifecycle methods will be deprecated. Either the code in VideoPlayer.js should be rewritten to not use these lifecycle methods or a quick fix would be to prefix them with ``UNSAFE_``, as this will still remain working also in the new React release. https://reactjs.org/blog/2019/08/08/react-v16.9.0.html

VideoPlayer.js
```
    /**
     * Before mounting, init our seekbar and volume bar
     * pan responders.
     */
    UNSAFE_componentWillMount() {
        this.initSeekPanResponder();
        this.initVolumePanResponder();
    }

    /**
     * To allow basic playback management from the outside
     * we have to handle possible props changes to state changes
     */
    UNSAFE_componentWillReceiveProps(nextProps) {
        if (this.state.paused !== nextProps.paused ) {
            this.setState({
                paused: nextProps.paused
            })
        }

        if(this.styles.videoStyle !== nextProps.videoStyle){
            this.styles.videoStyle = nextProps.videoStyle;
        }

        if(this.styles.containerStyle !== nextProps.style){
            this.styles.containerStyle = nextProps.style;
        }
    }
```

**Comment by TalonHughes13** [comment]
You could always put in a PR

**Comment by ravaliKs** [comment]
Hi Kristine and Kylemilloy,
Will this library support for react native 0.61 version, the video from s3 Url is taking long time to load.
