### ISSUE TITLE
Is there a way to disable the controls animation when you press the video?

### ISSUE THREAD

**Issue by nathandraper** [itsnubix/react-native-video-controls#172]
When you press the video, the player controls do this little animation where they bite down/fly away from the video component. Is there a way to change this behavior? It looks odd with my app layout.

**Comment by TeslaAjinkya** [comment]
> When you press the video, the player controls do this little animation where they bite down/fly away from the video component. Is there a way to change this behavior? It looks odd with my app layout.

yes,the fadeout animation looks odd on app video

**Comment by kylemilloy** [comment]
There is now in v2.5
