### ISSUE TITLE
useNativeDriver was not specified warning

### ISSUE THREAD

**Issue by fabio-C** [itsnubix/react-native-video-controls#178]
I am using this library with React 0.62.2, and I receive a lots of warning:

"Animated: 'useNativeDriver' was not specified. This is a required option and must be explicity set to true or false".

Found the same issue by another user in Stackoverflow
https://stackoverflow.com/questions/61709022/react-native-video-controls-warning-animated-usenativedriver-was-not-specifie

Is this library ok for react native > 0.6 ?

**Comment by kylemilloy** [comment]
It'll work with RN 60+...I'll patch out the error.

**Comment by kylemilloy** [comment]
Resolved as of v2.5
