### ISSUE TITLE
Warnings: "Animated: 'useNativeDriver' was not specified. This is a required option ..."

### ISSUE THREAD

**Issue by zenjedi** [itsnubix/react-native-video-controls#179]
Thanks *itsnubix* team for your 'react-native-video-controls' package. It's pretty good. 

I get a few warnings after having included your package. One of the main ones says:

> 

Animated: 'useNativeDriver' was not specified. This is a required option and must be explicitly set to 'true' or 'false'.

> 

Flagging here hoping there would be an update planned soon.

![image](https://user-images.githubusercontent.com/64598065/81922453-c43dc800-95f9-11ea-8c60-6cb8efd0fd4e.png)

**Comment by fabio-C** [comment]
I got the same error.

**Comment by kylemilloy** [comment]
Dupe #178
