### ISSUE TITLE
Multiple instances of video 

### ISSUE THREAD

**Issue by kamleshchandnani** [itsnubix/react-native-video-controls#18]
If I use multiple instances of videoplayer using the map 

```
this.state.videos.map(Video)

export const Video = (data) => {
...
}

```
then how to restrict only ONE video to play at a time?

**Comment by kylemilloy** [comment]
When we built this we only considered having one fullscreen video playing at a time...typically in a separate view. What's your use case? Scroll view with multiple videos?

**Comment by kamleshchandnani** [comment]
@kylemilloy Yes exactly Scroll view with multiple videos

**Comment by kylemilloy** [comment]
Let me look into this and I’ll see how say it is to add…if anything we take it on as a feature request.

K.


On Feb 23, 2017, at 12:02 AM, Kamlesh Chandnani <notifications@github.com<mailto:notifications@github.com>> wrote:


@kylemilloy<https://github.com/kylemilloy> Yes exactly Scroll view with multiple videos

**Comment by kylemilloy** [comment]
This is not going to be an intended use for this package. Please feel free to fork the repo.
