### ISSUE TITLE
"Video unavailable" with cross icon is not disappear,even we go back and play new video.Then new video is playing but that text with cross icon is not disappearing 

### ISSUE THREAD

**Issue by ZaidQ797** [itsnubix/react-native-video-controls#182]
When I play a video it works when I play a video which doesn't exist it shows "Video Unavailable" on the player and when I try to play another video which exists then video plays but that "VIDEO UNAVAILABLE" is not disappearing on new video

![Screenshot_20200622_233537_com cexzlex](https://user-images.githubusercontent.com/53520463/85323405-61392e00-b4e1-11ea-867a-a816cd5bf908.jpg)

**Comment by kylemilloy** [comment]
Can you share your code?

**Comment by alexakasanjeev** [comment]
![Screenshot_1596719915](https://user-images.githubusercontent.com/13250741/89536544-b1601b80-d815-11ea-9e76-448bdd7b6c3d.png)

Hello @kylemilloy The same is happening, if I turn of internet, I see a "video unavailable" error, but if I turn on internet, and then again try to play video by pressing play button, or changing seekbar value, video starts playing but "Video unavailable" message doesn't go away

**Comment by vicheanak** [comment]
Do This
`<VideoPlayer
        source={{uri: currentVideoUrl ? `${SOURCE + currentVideoUrl}` : null}} />
