### ISSUE TITLE
onHideControls fired only on screen tap

### ISSUE THREAD

**Issue by martinriviere** [itsnubix/react-native-video-controls#183]
onHideControls is only called in toggleControls method, which is called when user taps on screen.
It might be interesting to also fire it in hideControls method which is called by timeout so event is fired in any case.

Thanks for your great work!

**Comment by Michael24884** [comment]
Bump

**Comment by endifai** [comment]
Nice idea, it will solve many problems with using your library

**Comment by kylemilloy** [comment]
Fixed in #190
