### ISSUE TITLE
Unmet peer dependency

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [itsnubix/react-native-video-controls#192]
Hi

First of all: Thanks for an awesome lib! 😄 

I think you should update the peer dependency version of react-native-video from `^2.0.0` to something like `>=2.0.0` if you are confident with that, or just bump it to the newest major version of `react-native-video` with `^5.0.0`. Otherwise `npm list` gives errors about unmet peer dependency when using anything above `^2.0.0`. 

Best regards
Jens

**Comment by kylemilloy** [comment]
Hello again Jens. Sure....I think that's doable...gimme a sec.
