### ISSUE TITLE
Video display as black screen

### ISSUE THREAD

**Issue by codal-mpawar** [itsnubix/react-native-video-controls#225]
https://github.com/react-native-video/react-native-video/issues/2416

I comment on react-native-video issue. Please guys help me on that.
@kylemilloy @lopezjurip 
@slawo @friederbluemle @RWOverdijk 
@batusai513 
![IMG_0286](https://user-images.githubusercontent.com/46340921/124867307-73e2b000-dfdb-11eb-86c7-a9cc1cf5827e.PNG)

**Comment by kylemilloy** [comment]
Hey dude -- I'm all for helping you out but you gotta make it easier for us, you can't just spam a bunch of names post a screenshot and expect solutions. We don't know what you're running, what code you've written or anything else.

**Comment by codal-mpawar** [comment]
<VideoPlayer
 ref={(reference) => {
  if (reference) {
   videoRef = reference.player.ref;
  }
 }}
 source={{
  uri: props.videoUrl
 }}
 onLoad={() => {
  if (videoRef) {
   videoRef.seek(props.currentTime);
  }
 }}
 repeat
 onPlay={() => {
  setPlayPause(false);
 }}
 onPause={() => {
  setPlayPause(true);
 }}
 onError={(error) => {
  console.log("On Video error :: ", error)
 }}
 paused={paused}
 onProgress={_onProgress}
 onBack={() => _onBack()}
 resizeMode='contain'
 toggleResizeModeOnFullscreen={false}
 onEnterFullscreen={() => {
  changeState({ fullScreen: !fullScreen });
 }}
 disableFullscreen
/>
@kylemilloy This my code let me know if i am doing something wrong.

**Comment by kylemilloy** [comment]
This all looks good I would assume the issue is at the manifest file. Can you provide the details on how that's hosted?

**Comment by codal-mpawar** [comment]
@kylemilloy 
here is my manifest file
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:tools="http://schemas.android.com/tools"
  package="__APP_BUNDLE_ID__">

    <uses-permission android:name="android.permission.INTERNET" />
    
    
    
    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-feature android:name="android.hardware.camera" android:required="false" />
    <uses-feature android:name="android.hardware.camera.front" android:required="false" />
    <uses-permission-sdk-23 android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission-sdk-23 android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-feature android:name="android.hardware.camera.autofocus"/>
    <uses-permission android:name="android.permission.RECORD_AUDIO"/>
    <uses-permission android:name="android.permission.FLASHLIGHT"/>
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="com.android.vending.BILLING" />
    <permission
        android:name="__APP_BUNDLE_ID__.permission.C2D_MESSAGE"
        android:protectionLevel="signature" />
    <uses-permission android:name="__APP_BUNDLE_ID__.permission.C2D_MESSAGE" />
    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme"
      android:requestLegacyExternalStorage="true">

      <meta-data android:name="voxeet_use_invertase_react-native-firebase" android:value="true" />
      <meta-data android:name="voxeet_use_zoOr_react_native_push_notifications" android:value="true" />
      <meta-data android:name="voxeet_incoming_accepted_class" android:value="__APP_BUNDLE_ID__.MainActivity" />
      <meta-data
          tools:replace="android:value"
          android:name="com.google.firebase.messaging.default_notification_channel_id"
          android:value="IncomingVideoConference"/>
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:exported="true"
        android:windowSoftInputMode="adjustResize">
      </activity>
      <activity
      android:name="com.zoontek.rnbootsplash.RNBootSplashActivity"
      android:theme="@style/BootTheme"
      android:launchMode="singleTask">
      <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>

      <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="__SCHEME__" />
      </intent-filter>

      
      <intent-filter>
          <data android:scheme="__SCHEME__" />
          <action android:name="android.intent.action.VIEW" />
          <category android:name="android.intent.category.DEFAULT" />
          <category android:name="android.intent.category.BROWSABLE" />
      </intent-filter>

      
      <intent-filter android:autoVerify="true">
          <action android:name="android.intent.action.VIEW" />
          <category android:name="android.intent.category.DEFAULT" />
          <category android:name="android.intent.category.BROWSABLE" />
          <data android:scheme="https" android:host="__DEFAULT_DOMAIN_LINK__" />
      </intent-filter>

      </activity>
      <meta-data  android:name="com.dieam.reactnativepushnotification.notification_foreground"
                    android:value="false"/>
        
        <meta-data  android:name="com.dieam.reactnativepushnotification.notification_color"
                    android:resource="@color/white"/> 

        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationActions" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationPublisher" />
        <receiver android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationBootEventReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.QUICKBOOT_POWERON" />
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
            </intent-filter>
        </receiver>
        <service android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationRegistrationService"/>
        <meta-data android:name="com.dieam.reactnativepushnotification.default_notification_icon"
            android:resource="@mipmap/ic_stat_ic_launcher_foreground" />
    <meta-data
      android:name="com.dieam.reactnativepushnotification.default_notification_channel_id"
      android:value="@string/default_notification_channel_id" />
        <service
            android:name="com.dieam.reactnativepushnotification.modules.RNPushNotificationListenerService"
            android:exported="false" >
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>


      <meta-data android:name="io.branch.sdk.BranchKey" android:value="__BRANCH_KEY__"/>
      <meta-data android:name="io.branch.sdk.BranchKey.test" android:value="key_test_edwDakKcMeWzJ3hC3aZs9kniyuaWGCTa"/>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>

**Comment by codal-mpawar** [comment]
Please help me if you have a solution. @kylemilloy

**Comment by codal-mpawar** [comment]
@kylemilloy I hope to review the manifest code I shared with you still I am getting the same issue I will reopen the issue again.

**Comment by bmitioglov** [comment]
@codal-mpawar were you able to fix?

**Comment by codal-mpawar** [comment]
@bmitioglov currently we are not facing this issue.
