### ISSUE TITLE
Cannot get full screen mode working correctly on android.

### ISSUE THREAD

**Issue by dtully** [itsnubix/react-native-video-controls#23]
I'm working with react-native 0.41.2. On android, I cannot get the video to go full screen when clicking on the full screen icon. It only fills its parent's view instead of the entire screen. I'm sure this is probably a CSS issue but I can't figure it out. Does anyone have any advice for me? I'm new to react-native so I'm sure I'm missing something.

**Comment by gattigaga** [comment]
You should build your own to make it fullscreen, you can use react-native-orientation to lock orientation to landscape or portrait and hide several component. I am doing this at work.

**Comment by GarryLaly** [comment]
I've some problem, anyone can help me?

**Comment by valeriaabo** [comment]
Try using [react-native-fit](https://github.com/tibbus/react-native-fit) for full scrren. Its working for me in Android (AVD), still need to test it on a real device though.

**Comment by kylemilloy** [comment]
remove flex: 1 from the container.

**Comment by kylemilloy** [comment]
Removing flex from the parent container seems to fix this but if you nest it within another element with flex it'll contain it again.
