### ISSUE TITLE
Player invisible

### ISSUE THREAD

**Issue by 3DJakob** [itsnubix/react-native-video-controls#230]
I'm trying to use this module. I'm using it like the snippet below:
```
<VideoPlayer
        style={{ width: 200, height: 100 }}
        source={{ uri: CDNLink }}
/>
```
However, I can hear the video playing but the player is not visible. I tried to add a height and width with style but still nothing. Do you know why this might be? Also when using hooks how do I pass the `navigator` prop?

**Comment by alexDevBR** [comment]
I had this issue when the player was inside an empty `<View>`. Removing the View solved it.
