### ISSUE TITLE
Error loading video

### ISSUE THREAD

**Issue by jose920405** [itsnubix/react-native-video-controls#27]
Hi,

![simulator screen shot 24 06 2017 4 42 32 p m](https://user-images.githubusercontent.com/12536184/27512126-2ae73516-58fc-11e7-9774-ad802e33ab80.png)

i'm considering this line:

`If you're using RN < 39 run npm install --save react-native-video-controls@1.0.1`

but my version is exactly `0.39`.

**Comment by kylemilloy** [comment]
Have you linked the video components as per the doc at https://github.com/react-native-community/react-native-video ?

**Comment by jose920405** [comment]
@kylemilloy 

Of course, try both options. Manual and automatic link

**Comment by kylemilloy** [comment]
https://github.com/react-native-community/react-native-video/issues/184

How about trying this?

**Comment by Sundin** [comment]
I run `react-native link react-native-video` one more time, and then it worked.
