### ISSUE TITLE
Spotify Stops when I open RN app that uses react-native-video-controls lib

### ISSUE THREAD

**Issue by DjordjePetrovic** [itsnubix/react-native-video-controls#271]
I don't see 

https://www.npmjs.com/package/react-native-video#mixWithOthers
https://www.npmjs.com/package/react-native-video#ignoresilentswitch

Props being exposed within your lib, is there an ability to set them through your lib?

**Comment by kylemilloy** [comment]
https://github.com/itsnubix/react-native-video-controls/blob/master/VideoPlayer.js#L1219

All props get passed through.
