### ISSUE TITLE
Mute button

### ISSUE THREAD

**Issue by valeriaabo** [itsnubix/react-native-video-controls#28]
I need a **mute button** and remove the volume control.  Can't figure it out hot to create the mute button. 
Has anyone done this? Thanks in advance.

**Comment by kylemilloy** [comment]
I’d suggest you fork the project and modify the renderVolume code to be a toggle switch instead. Overriding it by using the renderControl method, a custom image and then a boolean gate to set the volume to 1 or 0 would be how I’d do it. this.state.muted should track whether or not it should be muted.

Let me know if this works for you.

On Jun 29, 2017, at 2:30 PM, valeriaabo <notifications@github.com<mailto:notifications@github.com>> wrote:


I need a mute button and remove the volume control. Can't figure it out hot to create the mute button.
Has anyone done this? Thanks in advance.

**Comment by valeriaabo** [comment]
@kylemilloy 
Thanks for the idea, I get the point :) But because Im a frontend I think it will be difficult for me to get it done like that,  Im gonna try it. 

If anybody else has it I will appreciate the code/help.

**Comment by kylemilloy** [comment]
No time like the present to learn something new :)

First start with forking...then create a new method like 

```
renderMuteButton() {
    let source = this.state.muted === true ? require( './assets/img/mute-on.png' ) : require( './assets/img/mute-off.png' );
        return this.renderControl(
            <Image source={ source } />,
            this.methods.toggleMute,
            styles.controls.muteButton
        );
}
```

You'll need to create a style for the mute button...start with just flexDirection: "row" and see how that works for you. Then you'll need some mute on/off icons

From there you'll need to create your toggleMute function as such:

```
toggleMute() {
    let state = this.state;
    state.muted = !state.muted;
    this.setState(state);
}
```

Finally you need to add this into the rendering method...look at renderTopControls in the JS file and you'll see a call in there called { renderVolume() }...replace this with your new renderMuteButton() method.

Hope this helps!

**Comment by valeriaabo** [comment]
@kylemilloy 
Thanks a lot 👍

**Comment by valeriaabo** [comment]
Sorry to bother again... I have it all but Im getting this error:
 "undefined is not a function ( evaluating 'callback()')"
Do you think im missing somehting?

And where should I  set the volume to 1 or 0? I think Im missing this.

**Comment by kylemilloy** [comment]
Changing between this.state.muted true/false automatically sets your volume from 0 to 1 and vice versa....already included so don't worry about it.

Can you show me your code in a pastebin or something?

**Comment by kylemilloy** [comment]
That said...evaluating callback as undefined likely means that whatever you're passing to the renderControl function as the callback isn't defined.


```
return this.renderControl(
        <Image source={ source } />,
        this.toggleMute, // This is the callback
        styles.controls.muteButton
    );
```

if you don't have a toggleMute() function in the VideoPlayer class it'll throw an error.

**Comment by valeriaabo** [comment]
Sure, this is my code https://pastebin.com/0sHB7M1b

Now Im getting a -8evaluating'state.muted'), Im going nuts :(

**Comment by kylemilloy** [comment]
Lemme boot this up and see what I can do.

**Comment by kylemilloy** [comment]
Try this: https://pastebin.com/HJjMu1WL

**Comment by kylemilloy** [comment]
That's my bad actually...the "this" keyword inside the toggleMute button wasn't bound to the component so it couldn't access the state property...weird OOP dark magic stuff. I registered the toggleMute command in the constructor in this pastebin so it now tracks state properly...tested in iOS quickly and it looks good. I enabled flex: 1 again on the container so you may want to take that off if you're on android.

**Comment by valeriaabo** [comment]
Don't worry about it.  **It works!!!** You SAVED me though. Thanks a lot!!!

**Comment by kylemilloy** [comment]
np.
