### ISSUE TITLE
Setting volume to 0 doesn't work

### ISSUE THREAD

**Issue by HsanBenJobrane** [itsnubix/react-native-video-controls#29]

**Comment by kylemilloy** [comment]
Define "doesn't work"

What are you expecting it to do, what's happening? Can you post some example code? Can you let me know what version of the package and what version of RN you're running?

**Comment by Thanmai-C** [comment]
I have the same problem, moving sound slider to 0 and again moving it up to max,
the sound still remains muted.
(The sound doesnt match according to the adjustment of sound slider most of the times)
I am using ur latest version of react native video controls and , RN:0.46.4.

Please help resolve this issue.

**Comment by 1uokun** [comment]
Maybe https://github.com/itsnubix/react-native-video-controls/pull/134 can help you
