### ISSUE TITLE
Video plays automatically in Android

### ISSUE THREAD

**Issue by abhideepmallick** [itsnubix/react-native-video-controls#32]
Video plays automatically in Android without user interaction. `playWhenInactive={ false }` prop does not work in android. What should be the solution/work around?

**Comment by kylemilloy** [comment]
That's the wrong prop. Use `paused={true}`

**Comment by abhideepmallick** [comment]
@kylemilloy the suggested prop does not work for Android. Also, the video starts preloading in Android, which causes a significant delay in rendering the View. I want something like; the video loads and plays only when the user clicks it, not otherwise. We should re open the issue? My current code: `<VideoPlayer
                source={{ uri: 'https://vjs.zencdn.net/v/oceans.mp4' }}
                navigator={this.props.navigator}
                paused={ true }
              />`
