### ISSUE TITLE
Cannot read property 'Constants' of undefined

### ISSUE THREAD

**Issue by AlmogRnD** [itsnubix/react-native-video-controls#34]
I'm getting the following error "cannot read property 'Constants' of undefined"

Not sure what's wrong here is my code 

```
{isVideo &&
                <VideoPlayer
                    source={{uri: 'https://s3-ap-southeast-2.amazonaws.com/ccapp-static-vidoes/' + selectedPhoto.filename}}
                />
                }
```

**Comment by Albinzr** [comment]
Im also having the same issue..

**Comment by kylemilloy** [comment]
Have you run `npm link react-native-video`?

**Comment by kylemilloy** [comment]
Try here 
https://github.com/react-native-community/react-native-video/issues/597

Or here
https://github.com/react-native-community/react-native-video/issues/438

Or here
https://github.com/react-native-community/react-native-video/issues/147
