### ISSUE TITLE
Seeking not working iOS

### ISSUE THREAD

**Issue by RWOverdijk** [itsnubix/react-native-video-controls#36]
Seeking doesn't work. Pressing once shows the controls, but the seek-bar is not responding to any of my touch gestures. Instead it only toggles the controls in / out.

**Comment by kylemilloy** [comment]
Fixed in your pull...also this one that's already merged. https://github.com/itsnubix/react-native-video-controls/pull/35

I'll get to your pull later today after I've had some time to try it in Android/iOS. Thanks again for the commits.
