### ISSUE TITLE
Fullscreen doesn't work

### ISSUE THREAD

**Issue by Blah237** [itsnubix/react-native-video-controls#41]
The fullscreen button doesn't have any effect. Is this a known issue?

**Comment by kylemilloy** [comment]
Fullscreen expands the video to fill the screen (or view). What's the problem you're having?

**Comment by afilp** [comment]
@kylemilloy It does change the icon, etc. but only this. I have the video inside a View, which is just a small View inside a larger View. So I assume that "FullScreen" just enlarges the video within that small View and not inside the Main View of the Screen.
