### ISSUE TITLE
seekbar not work on ios

### ISSUE THREAD

**Issue by jiangbo2015** [itsnubix/react-native-video-controls#42]
touch seekbar can't work, how to use it

**Comment by azisuazusa** [comment]
actually, its also not work in android and I just found the solution, how to contribute to this repo?

**Comment by jiangbo2015** [comment]
just pull request or put you link here

**Comment by AnisDerbel** [comment]
+1

**Comment by kylemilloy** [comment]
What versions are you guys running?

**Comment by azisuazusa** [comment]
I run latest version with RN 0.45.0

**Comment by kylemilloy** [comment]
I'm working through these issues today...I might release a 2.* to work with create-react-native-app and react-native-video 2.0 as well...1.4.x is priority to fix existing bugs though.

**Comment by kylemilloy** [comment]
Resolved in v1.4.1
