### ISSUE TITLE
Hide fullscreen control

### ISSUE THREAD

**Issue by fendorio** [itsnubix/react-native-video-controls#44]
Is it possible to hide any of the controls? I.e. I'm using the component on a full-screen video already, this makes the full-screen control redundant in this example..

**Comment by kylemilloy** [comment]
Yes...you'll have to fork it though...then remove the `this.renderFullscreen()` call from `renderTopControls()`
```javascript
renderTopControls() {
        return(
            <Animated.View style={[
                styles.controls.top,
                {
                    opacity: this.animations.topControl.opacity,
                    marginTop: this.animations.topControl.marginTop,
                }
            ]}>
                <Image
                    source={ require( './assets/img/top-vignette.png' ) }
                    style={[ styles.controls.column, styles.controls.vignette,
                ]}>
                    <View style={ styles.controls.topControlGroup }>
                        { this.renderBack() }
                        <View style={ styles.controls.pullRight }>
                            { this.renderVolume() }
                            { this.renderFullscreen() } // remove this line
                        </View>
                    </View>
                </Image>
            </Animated.View>
        );
    }
```

**Comment by fendorio** [comment]
Interesting, thanks for the swift answer. I may implement this as a prop and create a PR.

**Comment by kylemilloy** [comment]
No problem…you’ve got good timing…just logged on to make review some recent activity before running off to the gym.


On Aug 22, 2017, at 7:47 AM, Lee Brindley <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it possible to hide any of the controls? I.e. I'm using the component on a full-screen video already, this makes the full-screen control redundant in this example..
