### ISSUE TITLE
Pause button doesn't work on Android

### ISSUE THREAD

**Issue by xvonabur** [itsnubix/react-native-video-controls#45]
With `paused={false}` video starts, but cannot be paused. With `paused={true}` video does not starts by pressing play button. `react-native-video` controls with `controls={true}` works fine with tested mp4 video.

Android 7.1.1. Simulator and real device

**Comment by kylemilloy** [comment]
Bug fixing today...I'll take a look...

**Comment by kylemilloy** [comment]
https://github.com/itsnubix/react-native-video-controls/issues/46
