### ISSUE TITLE
onError:  -1004

### ISSUE THREAD

**Issue by ganyangxing** [itsnubix/react-native-video-controls#47]
start to load， call error ：

{
    extra: -1004,
   what: 1
}

**Comment by kylemilloy** [comment]
This is a stream error with Android and the RN-Video package. See here:

https://github.com/react-native-community/react-native-video/issues/303
https://github.com/react-native-community/react-native-video/issues/716

**Comment by KingAmo** [comment]
![image](https://user-images.githubusercontent.com/29938227/103350213-31936000-4ada-11eb-92b0-99e9f1e79ddc.png)
same here:
error:
{
 extra: -1004
 what: 1
}
