### ISSUE TITLE
Allow manual replay functionality

### ISSUE THREAD

**Issue by nagyv** [itsnubix/react-native-video-controls#51]
Currently it's not possible to restart an already finished playback.

using `this.ref.seek(0)` it's possible to reset the Video state, but playback will not start again

It's easy to acheive playback to be started by handling props changes that would change the paused state set from props in the constructor

**Comment by fendorio** [comment]
Seems like a nice logical addition to the repo

**Comment by kylemilloy** [comment]
Would be nice to have a replay button pop up at the end in place of the play/pause button....I'll review your pull and maybe add some changes myself.

**Comment by nagyv** [comment]
you are welcome :)

**Comment by kylemilloy** [comment]
Thanks for this...good addition.

**Comment by johnnash999** [comment]
do we have this feature now . ?:)

**Comment by alpgokcek** [comment]
bump

**Comment by sayancitytech** [comment]
any progress?
