### ISSUE TITLE
Navigator

### ISSUE THREAD

**Issue by mikejthomas** [itsnubix/react-native-video-controls#54]
I am having a lot of issues getting the back function to work. I continue to get a undefined error. Is there a full implementation example somewhere? I would be interested to see exactly how the props should be passed in. I use the React Navigation in the rest of my app using the Stack Navigation, but am also unsure of how I can edit the _onBack function to use that instead of the native Navigator. Any help would be appreciated. Thanks! Below is my current Video (minus the init states)

![screen shot 2017-10-28 at 4 50 42 pm](https://user-images.githubusercontent.com/13549012/32138408-2c2d2afe-bc00-11e7-9a0f-d4a70eb70cd7.png)

**Comment by kylemilloy** [comment]
If you pass the function an onBack prop that will be used as the function to be called when the back button is pressed. 

Try consoling out `this.props.navigator` as well to ensure that there is indeed an object there and that it's not undefined.

**Comment by mikejthomas** [comment]
Got it. I actually was able to pass in a react navigation route into the callback, like so: 

`                        onBack={() => { navigate('Home')}}
`

Which is actually better as I didn't want to just go back one screen after the video anyway. Thanks for your help.
