### ISSUE TITLE
support for RN0.47.2

### ISSUE THREAD

**Issue by armandomendivil** [itsnubix/react-native-video-controls#56]
peer dep missing: react-native@0.47.2, required by react-native-video-controls@2.0.0

**Comment by armandomendivil** [comment]
it seems to be a problem with expo

**Comment by koswarabilly** [comment]
i am not using expo but i get the same error

**Comment by kylemilloy** [comment]
If you’re getting a missing dependency error run npm install on the missing dependency.


On Nov 29, 2017, at 8:17 PM, koswarabilly <notifications@github.com<mailto:notifications@github.com>> wrote:


i am not using expo but i get the same error

**Comment by kylemilloy** [comment]
Looks like this is a mistake by me...see here:

https://github.com/itsnubix/react-native-video-controls/issues/58
