### ISSUE TITLE
full screen 

### ISSUE THREAD

**Issue by ankitbisht143** [itsnubix/react-native-video-controls#57]
I am using react-native-video-controls. How to make video to full screen of device?

**Comment by kylemilloy** [comment]
On mobile so can’t confirm but I believe this is a bug with RN Video itself. You need to put the video player in a full screen container. Check the react-native-video git for details.

On Dec 2, 2017, at 9:39 AM, Ankit Singh Bisht <notifications@github.com<mailto:notifications@github.com>> wrote:


I am using react-native-video-controls. How to make video to full screen of device?

**Comment by kylemilloy** [comment]
Any luck?

**Comment by masume-khorani** [comment]
How to return seekbar to first  when video ends?

**Comment by kylemilloy** [comment]
Please open a new ticket for different issues and provide a description of what you're trying to do. Either looping the video or just returning the seekbar to 0, etc.

**Comment by kylemilloy** [comment]
Closing this for now....
