### ISSUE TITLE
for react native 0.49

### ISSUE THREAD

**Issue by buruhsd** [itsnubix/react-native-video-controls#58]
is this support for react native 0.49? i try this, but video cant load.

**Comment by kylemilloy** [comment]
Any logs?

On Dec 7, 2017, at 1:44 AM, muhammad al jawad <notifications@github.com<mailto:notifications@github.com>> wrote:


is this support for react native 0.49? i try this, but video cant load.

**Comment by clairekrogers** [comment]
I am also facing an issue and thinking it might be related to this.

I get the error `react-native-video-controls@2.0.0" has incorrect peer dependency "react-native@0.47.2"`

Here is the relevant portion of my package.json:

```json
"dependencies": {
    "react": "^16.0.0",
    "react-native": "^0.50.3",
    "react-native-video": "^2.0.0",
    "react-native-video-controls": "^2.0.0",
  },
```

Looking at the `package.json` for `react-native-video-controls` in my `node_modules/` folder, I see that indeed the peer dependency on react-native is for version 0.47.2. 

I see you updated the dependency to be `">=0.46.0"` in commit [80890f1](https://github.com/itsnubix/react-native-video-controls/commit/80890f1ee7975daece611f9f456d262a1c512f39), but running `yarn install` seems to pull the previous commit, where the version of this package was bumped but the dependency on react native was not ([576f3ff](https://github.com/itsnubix/react-native-video-controls/commit/576f3ff3b1d7a19901adb9f9b2a2abc56f583317)).  I get the package.json from this commit in my `node_modules/`.

It would appear that the latest version of this package is not hosted on npm.  @kylemilloy can you verify that the version npm is hosting has the most recent commit?

In case it's useful, from my yarn.lock:
```
react-native-video-controls@^2.0.0:
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/react-native-video-controls/-/react-native-video-controls-2.0.0.tgz#c4fc42b7f42471ff23fd3c4bb1e3d9055d305272"
  dependencies:
    lodash "^4.16.4"
```

Thank you!

**Comment by buruhsd** [comment]
okay, thank you

**Comment by kylemilloy** [comment]
Good catch. 2.0.1 coming right up....

**Comment by clairekrogers** [comment]
That fixed it!  Thank you for the very quick response!!
