### ISSUE TITLE
togglePlayPause on iOS

### ISSUE THREAD

**Issue by mikejthomas** [itsnubix/react-native-video-controls#60]
I am having issues with the pause button, but only on iOS using the exact same code. It is a huge mystery to me. An example of the code is below (I have several videos). Do I need a prop for the toggle? Am I just lucky that it is working in android? or...is there something I need to do in the xcode project?

Thanks in advance!

`                    <VideoPlayer
                        source={{ uri: 'https://firebasestorage.googleapis.com/v0/b/...' }}
                        style={styles.fullScreen}
                        rate={this.state.rate}
                        volume={this.state.volume}
                        muted={this.state.muted}
                        ignoreSilentSwitch={this.state.ignoreSilentSwitch}
                        resizeMode={this.state.resizeMode}
                        onLoad={this.onLoad}
                        onBuffer={this.onBuffer}
                        onProgress={this.onProgress}
                        repeat={true}
                        onBack={() => { navigate('Home'), this.state.paused = true}}
                    />`

**Comment by kylemilloy** [comment]
What’s the issue? Not pausing? Not playing after pause?

On Dec 9, 2017, at 4:51 PM, Michael Thomas <notifications@github.com<mailto:notifications@github.com>> wrote:


I am having issues with the pause button, but only on iOS using the exact same code. It is a huge mystery to me. An example of the code is below (I have several videos). Do I need a prop for the toggle? Am I just lucky that it is working in android? or...is there something I need to do in the xcode project?

Thanks in advance!

<VideoPlayer source={{ uri: 'https://firebasestorage.googleapis.com/v0/b/...' }} style={styles.fullScreen} rate={this.state.rate} volume={this.state.volume} muted={this.state.muted} ignoreSilentSwitch={this.state.ignoreSilentSwitch} resizeMode={this.state.resizeMode} onLoad={this.onLoad} onBuffer={this.onBuffer} onProgress={this.onProgress} repeat={true} onBack={() => { navigate('Home'), this.state.paused = true}} />

**Comment by mikejthomas** [comment]
Oops, my bad. Its not pausing when you press the button. So, I guess the paused state isn’t being toggled as it should be, but I am not sure how or why.

**Comment by kylemilloy** [comment]
The play/pause functionality is a private method so there isn't a prop for it that you can set. Looks like you're changing your styles here...if you go into inspector and select the play/pause icon does it have a hitbox? Maybe your styles are overwriting something?

**Comment by kylemilloy** [comment]
Can you also do me a solid and add an error callback with the `onError` prop and see if it's spitting out anything that we can use?

**Comment by mikejthomas** [comment]
Sorry it took so long to get back on this, but it looks like it was actually the styles, like you said. Thanks again for your help.
