### ISSUE TITLE
How to return seekbar to first when video ends?

### ISSUE THREAD

**Issue by masume-khorani** [itsnubix/react-native-video-controls#61]
I used react-native-video-controls and I want to return seekbar to first when video ends. please help me

**Comment by kylemilloy** [comment]
Something like this. Don't forget to pause the video too if you don't want it to keep playing.


```
class MyComponent extends Component {
    constructor(props) {
        super(props);
        this.controls = VideoPlayer;
    }

    onEnd() {
        this.controls.seekTo(0);
    }

    render() {
        return <VideoPlayer ref={ controls => this.controls = controls} onEnd={ this.onEnd } />;
    }
}
```

**Comment by kylemilloy** [comment]
Closing...

**Comment by maxschmeling** [comment]
This isn't working on Android. It does allow me to play, but it doesn't actually set the seek bar visually back to the beginning (though the video does go back to the beginning).

**Comment by kylemilloy** [comment]
Will need to fire an update
