### ISSUE TITLE
[iOS] Video duration, seek, preloader dont' work

### ISSUE THREAD

**Issue by nmorozov** [itsnubix/react-native-video-controls#62]
Hi! I just installed this beautiful module and faced some issued.

On android it works properly, but on iOS does not.

Issues:
1) Duration always 0, _onLoad method does not fire
2) Seek bar does not work. I can move it but nothing happens
3) There is no preloader

package.json
```
    "react-native": "^0.48.4",
    "react-native-video": "^2.0.0",
    "react-native-video-controls": "^2.0.1",
    "react-navigation": "^1.0.0-beta.15"
```

```
Module usage
          <VideoPlayer
          source={{ uri: 'https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8' }}
          onBack={() => { this.props.navigation.goBack()}}
          style={{height: 230}}
        />
```

Devices:
Iphone 4s
Iphone 5s (emulator)

**Comment by kylemilloy** [comment]
Thanks for adding all this detail...makes debugging a lot easier.

I suspect the issue is with your video's encoding. 

You're using HLS, which should work with Apple, however the parameters on the encode itself need to change. Looking at the encode on one of the 1080p segments gets us the following:

![MediaInfo](https://i.imgur.com/OYWFm1d.png)

As we can see it's using a Level 5 Main profile encoding...try redoing the encoding at Main 4.1 for backwards compatibility. 

As you can see in the screenshots from the Apple Support pages, iPhone 4s supports 4.1 and 5s supports 4.2.

![iPhone4s](https://i.imgur.com/KArAuR0.png)

![iPhone5s](https://i.imgur.com/f8Xc40f.png)

**Comment by kylemilloy** [comment]
Try adding an onError callback and console out what iOS is sending back...might help you find the culprit as well.

**Comment by kylemilloy** [comment]
[Check out this page](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StreamingMediaGuide/UsingHTTPLiveStreaming/UsingHTTPLiveStreaming.html) for encoding details on iOS devices.

Skip down to the heading **Preparing Media for Delivery to iOS-Based Devices** for the technical details.

**Comment by nmorozov** [comment]
@kylemilloy 
1) I change video uri to https://vjs.zencdn.net/v/oceans.mp4 (from Readme) same issues
2) Added onError and there are no errors
😄 

May be is it react-native-video module issue? https://github.com/react-native-community/react-native-video/issues/859

**Comment by kylemilloy** [comment]
Haha. Well damn...lemme think about it some more.

**Comment by kylemilloy** [comment]
You ran `react-native link` on the package already eh? What other things do you have going on in your app?

Here's a screenshot that I just tested:

![iPhone 5s emulator](https://i.imgur.com/4U7s8WT.png)

Here's the code:

```
export default class App extends Component<{}> {
  constructor(props) {
    super(props);

    this.controls = VideoPlayer;
  }

  render() {
    return (
      <View>
        <View style={{height: 400}}>
          <VideoPlayer
              source={{ uri: 'https://vjs.zencdn.net/v/oceans.mp4' }}
              navigator={ this.props.navigator }
              ref={controls => this.controls = controls}
          />
        </View>
        <View style={{height: 200}}>
          <TouchableHighlight
            onPress={() => {
              console.warn('asdf');
              console.warn(this.controls.player.ref);
              console.warn(this.controls);
            }}
            activeOpacity={0.5}
            style={{backgroundColor: 'red'}}
          >
            <Text>Press</Text>
          </TouchableHighlight>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
```

**Comment by nmorozov** [comment]
I have tried to use your code in my project and there are same issues. Then I created new project with create-react-native-app and paste your code... it works. It means that problem in my current project, I will try to find it. Thanks for your help
