### ISSUE TITLE
Always playing on background

### ISSUE THREAD

**Issue by franzejr** [itsnubix/react-native-video-controls#66]
I got this working and it's really good. Although, even when I'm setting `playInBackground` as false(and the default was also false), when I change the screen, the audio still playing..

Has anyone an idea?

Thanks,

**Comment by kylemilloy** [comment]
Android or iPhone?

**Comment by franzejr** [comment]
Apple. iPhone 7 Plus simulator, @kylemilloy

**Comment by kylemilloy** [comment]
Try using `playWhenInactive={false}`

Alternatively you could set a listener on [one of these events](https://facebook.github.io/react-native/docs/appstate.html) and force the video to pause through there.

**Comment by franzejr** [comment]
I used `playWhenInactive={false}` and it doesn't work :/. Also, this also didn't work for `react-native-video` only.

I will try to check these other events you pasted here. Thanks!

**Comment by franzejr** [comment]
@kylemilloy this also works when I go to another screen or when I go to the home screen. I think this might be an issue for `react-native-audio`.

**Comment by franzejr** [comment]
I tried also other libraries similar to your library and I got the same error. So, definitely, something on `react-native-video`. I will create a new project from scratch and simulate the error and see If I can fix it.

**Comment by kylemilloy** [comment]
Thanks bud.

**Comment by Thanmai-C** [comment]
I have the same issue on android phone as well

**Comment by kylemilloy** [comment]
Did you try tying listeners to app state changes as I suggested above?

https://facebook.github.io/react-native/docs/appstate.html

**Comment by franzejr** [comment]
I think the solution might be wiring up react navigation + redux and then we will know when the screen changes and with this, we can pause the video.

About app state, I didn't try it yet.

**Comment by franzejr** [comment]
So, I wired up this using React Native + Refud and everything worked fine.

**Comment by Thanmai-C** [comment]
@franzejr  can you share a snippet of how u did that?
