### ISSUE TITLE
nullControl: callback is not a function

### ISSUE THREAD

**Issue by wodCZ** [itsnubix/react-native-video-controls#67]
Hi,

Today I have implemented this package, and found one issue with hidden controls.

Problem is that when controls like back button are hidden, they still render Touchable zone with onPress callback, that expects callback (see [renderControl](https://github.com/itsnubix/react-native-video-controls/blob/master/VideoPlayer.js#L780-L798)), but [renderNullControl](https://github.com/itsnubix/react-native-video-controls/blob/master/VideoPlayer.js#L1011-L1017) doesn't pass any callback to renderControl. This causes error `callback is not a function` when you tap on location where back button touch zone is.

I'd suggest modifying `renderNullControl` to pass empty callback function to `renderControl` method, or to modify `renderControl` to check if `callback` is set.

Please let me know which variant you'd like more and whether you want me to prepare pull request.

Thanks!

**Comment by kylemilloy** [comment]
Thanks for this. I'm going to change renderNullControl to just return an empty `<View/>`.

Pushing up a fix now.

**Comment by wodCZ** [comment]
Awesome, thanks!
