### ISSUE TITLE
Timer control shows weird value when playing video with `.ts` format

### ISSUE THREAD

**Issue by yezarela** [itsnubix/react-native-video-controls#71]
![img_20180207_150440](https://user-images.githubusercontent.com/11919795/35905785-016fa312-0c1b-11e8-9628-19b2e952691b.jpg)

When i check the video data on `_onLoad` function, it returns `{ duration: -9223372036854776, ... }`

**Comment by kylemilloy** [comment]
How're you encoding the ts file? These are generally weird stream files...you might have to put an m3u8 file in front of it...though I can't recall where `react-native-video` has landed with support.

**Comment by kylemilloy** [comment]
Any luck?

**Comment by yezarela** [comment]
Hi @kylemilloy, finally i use m3u8 and it works fine, thanks..
