### ISSUE TITLE
How can I load a video from app-folder...for-example assets?

### ISSUE THREAD

**Issue by Turtle0601** [itsnubix/react-native-video-controls#80]
Hi,
I'll get the videos of the assets-file-folder from the react-native app. 

How can i do this with this component? 

Because, if i wrote the uri with URL to the folder, the video don't show, the player loads and loads, but don't play. 

for Example: source={{ uri: '/Recovered References/BigBuckBunny_512kb.mp4'}}

And can i change the option, that the video only starts, if i touch the play-button.

Thanks for help

**Comment by kylemilloy** [comment]
To load a video from your app folder use require:

source={{uri: require(‘path/to/video.mp4’)}}

To stop auto play on the video pass the paused prop to the component:

paused={ true }

See more here about video props you can pass through to the video: https://github.com/react-native-community/react-native-video

**Comment by Turtle0601** [comment]
Thanks for your help. 

I have test it ...your the source example isn't works. But it was the right way and take me to the solution. I figured out, this:

source={require('./assets/BigBuckBunny_512kb0.mp4')}

and it works! :)

Best Regards

**Comment by kylemilloy** [comment]
Sorry about that...was texting you from my phone so was going off memory...glad you got it figured out.

**Comment by Turtle0601** [comment]
No worries!
However it was helpful. 

:)

**Comment by kylemilloy** [comment]
Of course. Pass it like any variable.

**Comment by kylemilloy** [comment]
Sorry, I fail to see how this would make a difference...in the original code it's explicitly called out that source is passed, in the second we just rely on ...this.props.

How does this change this.props.source being used by the Video component?

**Comment by kylemilloy** [comment]
Yeah if you don't mind writing a PR I'd like to test this one myself. I'm having difficulty wrapping my head around how this changes anything. Maybe I'm reading your code wrong?

Here's what I'm understanding:

In the first we do:
```js
<Video 
  { ...this.props }
  source={ this.props.source }
/>
```
We explicitly call out source and pass it on.

In the second we do:
```js
<Video { ...this.props } />
```
And rely on passing the source with the spread operator with the rest of the props.

To me, it's the exact same thing...isn't it? 

Like, you can do...
```js
<VideoPlayer source={{ uri: 'path/to/file.mp4' }} />
```
...now already...what would this change?

**Comment by raphaelluiz128** [comment]
if i remove the line with "source={this.props.source}", it's ok to use       source={{uri: this.state.dir}} ? a dymamic local file ? i will select the file in a list and the path will stored in state dir, i have five videos and require is not dynamic
