### ISSUE TITLE
<Android> Video doesn't load

### ISSUE THREAD

**Issue by RCTnativeapp** [itsnubix/react-native-video-controls#82]
Video is not loading in Android device:

"react-native-video": "2.0.0",
"react-native-video-controls": "2.0.1",

03-20 10:34:43.444 23748-23748/? E/MediaPlayer: isPlaying: called in state MEDIA_PLAYER_STATE_ERROR
03-20 10:35:02.614 3693-25025/? E/GenericSource: [application/octet-stream]
03-20 10:35:02.689 3693-25028/? E/GenericSource: [video/quicktime]
03-20 10:35:05.399 3693-25028/? E/GenericSource: Failed to init from data source!
03-20 10:35:05.399 23748-23926/? E/MediaPlayer: error (1, -2147483648)
03-20 10:35:05.404 23748-23748/? E/MediaPlayer: Error (1,-2147483648)
03-20 10:35:07.114 4122-4946/? E/Watchdog: !@sync 1129 [03-20 10:35:07.123]

Any clue please.

**Comment by kylemilloy** [comment]
Can you show me your code?

**Comment by RCTnativeapp** [comment]
this.props.data.type=="video" &&
            <View style={[styles.videoContainer]}>
              <VideoPlayer source={{uri: this.props.data.videoUrl}}
                 ref={(ref) => { this._player = ref; }}
                 disableBack
                 disableVolume
                 rate={1.0}
                 volume={1.0}
                 muted={false}
                 paused={false}
                 resizeMode="contain"
                 repeat={true}
                 playInBackground={false}
                 playWhenInactive={false}
                 onLoad={this._videoLoaded.bind(this)}
                 onFullscreenPlayerWillPresent={(e) => {
                   this.setState({ videoFullscreen: true})
                 }}
                 onFullscreenPlayerWillDismiss={(e) => {
                   this.setState({
                     videoFullscreen: false,
                     autoVideoFullscreen: false
                   })
                 }}
                 style={styles.vidbit}/>
              { this.state.videoLoading &&
                <View style={{height: 250, justifyContent: 'center', alignItems: 'center'}}>
                  <Image style={{position: 'absolute',top: 0, left: 0, bottom: 0, right: 0}}
                    source={{uri: this.props.data.thumbnailUrl}}/>
                  {(this.state.viewRef == null ? null :
                  <BlurView style={{position: 'absolute',top: 0, left: 0, bottom: 0, right: 0}}
                     blurType="light"
                     blurAmount={10}/>)}
                  <ActivityIndicator size='large' color='#c6c6c6'/>
                </View>
              }
            </View>

**Comment by kylemilloy** [comment]
Where are you reading your documentation from? There are a bunch of props here that I'm not even sure do anything or that are just completely ignored.

Is your videoUrl prop a base64 string?
What happens inside your `_videoLoaded` function?

**Comment by RCTnativeapp** [comment]
Thanks.
hardcoding url to some online video, its able to load. 
as you mentioned videoUrl prop having issue.

Is your videoUrl prop a base64 string? videoURL prop is not declared as base64.

Added below proptype, but still not loading.
  static propTypes = {
		videoUrl: PropTypes.base64,
	};

Any issue you see with specific to uri data source videoURL.

  _videoLoaded() {
    this.setState({
      videoLoading: false
    });

    // override fullscreen button behavior to present fullscreen player
    // instead of just setting resizeMode
    this._player.methods.toggleFullscreen =
      this._player.player.ref.presentFullscreenPlayer;
  }

**Comment by kylemilloy** [comment]
Can you share with me your video url?

**Comment by RCTnativeapp** [comment]
you won't be able to access the link. Any other clue please

**Comment by kylemilloy** [comment]
Why not? Is it possible the app cannot access the link either?

**Comment by kylemilloy** [comment]
// Let's simplify what's going on here...replace your `<VideoPlayer/>` call with this and let me know if it works...we're removing some fullscreen callbacks that and the onLoad callback for now as that may be causing conflicts.

```js
<VideoPlayer
    source={{uri: this.props.data.videoUrl}}
    // disableBack                            <-- this needs a value
    // disableVolume                          <-- this needs a value
    // rate={1.0}                             <-- this is the default, no need to declare again
    // volume={1.0}                           <-- default
    // muted={false}                          <-- default
    paused={false}
    resizeMode="contain"
    repeat={true}
    // playInBackground={false}               <-- default
    // playWhenInactive={false}               <-- default
    // onLoad={this._videoLoaded.bind(this)}  <-- this might be causing a conflict...

    style={styles.vidbit}/>

    /**
     * Remove all of this, if you want to hook into the fullscreen
     * hooks use the latest package and read the documentation.
     * 
     * onFullscreenPlayerWillPresent={(e) => {
     *   this.setState({ videoFullscreen: true})
     * }}
     * onFullscreenPlayerWillDismiss={(e) => {
     *  this.setState({
     *     videoFullscreen: false,
     *     autoVideoFullscreen: false
     *   })
     * }}
    */
```


So truncated this will look like:

```js
<VideoPlayer
    source={{uri: this.props.data.videoUrl}}
    paused={false}
    resizeMode="contain"
    repeat={true}
    style={styles.vidbit}/>
```

**Comment by RCTnativeapp** [comment]
I replaced with the truncated code you have shared. But still it doesn't load.

Few more observations"
Hardcoding the video URL to external video(.mp4) works.
Hardcoding the video the video I am referring from data.videourl doesn't load. our video is mov format.

Also its specific to few android devices above version 6.0.1

**Comment by kylemilloy** [comment]
Android doesn't support .mov

https://developer.android.com/guide/topics/media/media-formats.html

**Comment by RCTnativeapp** [comment]
thanks..will check
