### ISSUE TITLE
onEnterFullscreen is not working 

### ISSUE THREAD

**Issue by somsin** [itsnubix/react-native-video-controls#83]
i am using to play video in app. all is working fine but onEnterFullscreen call is not happing when i want to go in full screen mode , 

<VideoPlayer
                            source={{ uri: video_link }}
                            navigator={ this.props.navigator }
                            style={ {height: 300, overflow:'hidden'} }
                            paused={true}
                            volume={1.0}
                            repeat={false}
                            muted={false}
                            playWhenInactive={false}
                             onPlay={ () => {{console.log('onPlay')}} }
                             onBack={ () => {{console.log('onBack=')}} }
                             onEnd={ () => {{console.log('onEnd=')}} }
                             onError={ () => {{console.log('onError')}} }
                             onExitFullscreen={ () => {{console.log('onExitFullscreen',)}} }
                             onEnterFullscreen={()=> {console.log('clicked',)}}
                        />
onEnterFullscreen={ () => {} }   // Fired when the video enters fullscreen after the fullscreen button is pressed
    onExitFullscreen={ () => {} }

**Comment by kylemilloy** [comment]
Which version of the app are you using? Looks like you have some extra brackets in there too

**Comment by kylemilloy** [comment]
So I tested your code a bit with a vanilla install and it seems to be working fine...here's my package.json...note that I'm using v.2.2.0 of `react-native-video-controls` which is where the on(Enter/Exit)Fullscreen events became available...it's not in any earlier packages. If you swap these to console.log statements to console.warn you'll also see the errors pop on the actual screen vs. in the logger.

```js
{
  "name": "test",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "^16.3.0-alpha.1",
    "react-native": "0.54.2",
    "react-native-video": "^2.0.0",
    "react-native-video-controls": "^2.2.0"
  },
  "devDependencies": {
    "babel-jest": "23.0.0-alpha.0",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.2",
    "react-test-renderer": "^16.3.0-alpha.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by somsin** [comment]
after updating "react-native-video-controls": "^2.2.0"  onEnterFullscreen fired but still video not moving in fullscreen

**Comment by kylemilloy** [comment]
I've addressed this issue here.
https://github.com/itsnubix/react-native-video-controls/issues/85

**Comment by varunnn-m** [comment]
change the version in package.json to "2.7.1", and remove the "^" symbol before the version number, it will work
