### ISSUE TITLE
Fullscreen only zooms in

### ISSUE THREAD

**Issue by rasselll** [itsnubix/react-native-video-controls#85]
When i click full screen mode it only zooms into the video and does not fill the entire device screen 

      <Content>
      <VideoPlayer source={require('../video/video.mp4')}
      style={{ width: Dimensions.get('window').width, height: 200}}
      navigator={ this.props.navigator }/>
      <Content>

**Comment by zerophilip** [comment]
me too!!!!

**Comment by zerophilip** [comment]
_toggleFullscreen() {
        let state = this.state;

        state.isFullscreen = ! state.isFullscreen;
        state.resizeMode = state.isFullscreen === true ? 'cover' : 'contain';

        if (state.isFullscreen) {
            typeof this.events.onEnterFullscreen === 'function' && this.events.onEnterFullscreen();
        }
        else {
            typeof this.events.onExitFullscreen === 'function' && this.events.onExitFullscreen();
        }

        this.setState( state );
    }

Thats why only zooms in?

**Comment by somsin** [comment]
how to fix that issue , is there any way to resolve

**Comment by kylemilloy** [comment]
Fullscreen is a bit of a misnomer.. When we originally built this for a project our use case was that the video player was the only component on the page, therefore "full screen" meant that the video fills the screen (no black bars) or plays unzoomed. 

We added enter/exit hooks so that people could add their own functionality to this. To make it fill the screen you'll need to do something like:


```js
class MyComponent extends Component {
  onEnterFullscreen() {
    let state = this.state;
    state.isFullscreen = true;
    this.setState(state);
  }

  onExitFullscreen() {
    let state = this.state;
    state.isFullscreen = false;
    this.setState(state);
  }

  render() {
    return (
      <View style={[
        this.state.isFullscreen ? styles.player.fullscreen : styles.player.embedded
      ]}>
        <VideoPlayer 
          onEnterFullscreen={ this.onEnterFullscreen.bind(this) } 
          onExitFullscreen={ this.onExitFullscreen.bind(this) } 
        />
      </View>
    );
  }
}

const styles = {
  player: StyleSheet.create({
    fullscreen: {
      // Style in a way that it's fullscreen
    },
    embedded: {
      // Style in a way that it's embedded into the page
    }
  })
}
```

**Comment by somsin** [comment]
here is my code . its not work  
constructor(props){
        super(props);
        this.state ={
            isFullscreen: this.props.isFullscreen || false

        }
    }

// Do whatever manipulation you need when entering fullscreen
  enterFullscreen() {
    let state = this.state;
    state.isFullscreen = true;
    this.setState(state);
  }

  // Do whatever manipulation you need when exiting fullscreen
  exitFullscreen() {
    let state = this.state;
    state.isFullscreen = false;
    this.setState(state);
  }


 <View style={styles.cardMain}>
<View style={[this.state.isFullscreen ? styles.player.fullscreen : styles.player.embedded ]}>
<VideoPlayer
                            source={{ uri: this.props.video_link }}
                            navigator={ this.props.navigator }
                            style={ {height: this.state.height, overflow:'hidden'} }
                            paused={true}
                            volume={1.0}
                            repeat={false}
                            muted={false}
                            playWhenInactive={false}
                            onEnterFullscreen={ this.enterFullscreen.bind(this) } 
                            onExitFullscreen={ this.exitFullscreen.bind(this) } 
                        />

</View>
</View>

**Comment by kylemilloy** [comment]
If you're trying to get the video to go fullscreen with what you posted then I wouldn't expect it to work. The code here is incomplete. 

What you've posted here is essentially verbatim (ie - copy/paste) of what I posted above. In that post I mentioned that it will get you on the right path but it really doesn't do anything besides update the state of your component. You need to add functionality to it. To clarify **this code and the code I posted above won't make your video go fullscreen by itself**. What you need to do is add onto the code that I provided to achieve your desired outcome. 

I noticed that you're not using the stylesheet manipulation that I outlined which would likely be crucial to achieving a fullscreen display. To clarify...that is the bottom part that reads as:


```js
  // By default the VideoPlayer fills its parent, so have a parent view
  // stretch/shrink/rotate/move as needed to get that fullscreen.
  render() {
    return (
      <View style={[
        // ### This part here is very important ###
        this.state.isFullscreen ? styles.player.fullscreen : styles.player.embedded
      ]}>
        <VideoPlayer 
          onEnterFullscreen={ this.enterFullscreen.bind(this) } 
          onExitFullscreen={ this.exitFullscreen.bind(this) } 
        />
      </View>
    );
  }
}

// ### also very important here
const styles = {
  player: StyleSheet.create({
    fullscreen: {
      // Style in a way that it's fullscreen based on your app
      position: 'absolute'
      bottom: 0,
      right: 0,
      left: 0,
      top: 0,
    },
    embedded: {
      // Style in a way that it's embedded into the page how you have it
      position: 'relative',
      flex: 1
    }
  })
}
```

Help me help you. What are you trying to do? What isn't working?

**Comment by somsin** [comment]
yes ,i used 
 fullscreen: {
        // Style in a way that it's fullscreen based on your app
        position: 'absolute',
        bottom: 0,
        right: 0,
        left: 0,
        top: 0,
      },
      embedded: {
        // Style in a way that it's embedded into the page how you have it
        position: 'relative',
        flex: 1
      } , but just not posted in comment , its not working for me

**Comment by kylemilloy** [comment]
What are you trying to do? What isn't working? Are you getting any errors? What have you tried to do? How isn't it achieving your desired outcomes?

**Comment by kylemilloy** [comment]
Hey...any luck? Still having issues?

**Comment by kylemilloy** [comment]
I'm going to close this now for inactivity...let me know if you need more help.

**Comment by mobhupath** [comment]
I'm facing this issue too, any solution?

**Comment by mobhupath** [comment]
As an alternative, i'm opening video again in a brand new screen.

**Comment by 3KINGZ** [comment]
> ```js
> position: 'absolute'
>       bottom: 0,
>       right: 0,
>       left: 0,
>       top: 0,
> ```

@mobhupath how were you able to sync the videos?
