### ISSUE TITLE
How to play local video?

### ISSUE THREAD

**Issue by Ashi90** [itsnubix/react-native-video-controls#90]
I want to play local video , but when I pass it in source under VideoPlayer wrapper it's just navigate and nothing to play, Here is my code

` <VideoPlayer
    source={{ uri: 'assets-library://asset/asset.mov?id=046420B5-23CD-48BC-9DEC-52CD52B2C577&ext=mov' }}
    navigator={ this.props.navigator }

    controlTimeout={ 15000 }         // hide controls after ms of inactivity.
   navigator={ navigator }          // prop from React Native <Navigator> component
   seekColor={ '#FFF' }             // fill/handle colour of the seekbar
   videoStyle={ {} }                // Style appended to <Video> component
   style={ {} }                     // Style appended to <View> container

   // event callbacks
   onError={ () => {} }                     // Fired when an error is encountered on load
   onBack={ () => {this.backAction()} }     // Function fired when back button is pressed.
   onEnd={ () => {this.backAction()} }      // Fired when the video is complete.

   // disabling individual controls
   disableFullscreen={ false }      // Used to hide the Fullscreen control.
   disableSeekbar={ false }         // Used to hide the Seekbar control.
   disableVolume={ true }          // Used to hide the Volume control.
   disableBack={ false }            // Used to hide the Back control.
   disableTimer={ true }           // Used to hide the Timer control.
/>`

**Comment by kylemilloy** [comment]
Please read closed tickets regarding similar issue before opening a new one. 

https://github.com/itsnubix/react-native-video-controls/issues/80
