### ISSUE TITLE
check the render method of 'VideoPlayer'

### ISSUE THREAD

**Issue by CoderSwitch** [itsnubix/react-native-video-controls#91]
If the network link address is passed into the VideoPlayer component, it will crash. What is the reason for this? The code is consistent with the author?

**Comment by CoderSwitch** [comment]
![78169b8fccec438b3452a1f8e7229723](https://user-images.githubusercontent.com/24489900/38172116-da6fd90c-35d8-11e8-964f-df7654c6f3dd.jpg)

**Comment by kylemilloy** [comment]
Can you post your full code? I would start with consoling out the props you're passing the VideoPlayer. I would assume you're accidentally passing an undefined prop to it.

**Comment by kylemilloy** [comment]
Any updates here?

**Comment by CoderSwitch** [comment]
![1522824424064](https://user-images.githubusercontent.com/24489900/38292703-450f8b32-3817-11e8-9b35-448067aeb45a.jpg)
![1522824504884](https://user-images.githubusercontent.com/24489900/38292707-4a08f7f4-3817-11e8-8242-8373770890de.jpg)
Sorry, there's no real time update, so these two graphs are all code, and it's weird that the program just doesn't recognize this VideoPlayer.

**Comment by CoderSwitch** [comment]
[ExhibitWorks.js.zip](https://github.com/itsnubix/react-native-video-controls/files/1874742/ExhibitWorks.js.zip)

**Comment by kylemilloy** [comment]
+1 for screenshots and including your code here...lemme take a look and see if I can figure it out.

**Comment by kylemilloy** [comment]
Alright....so...here's my findings.

I can't get _this.videoUrl to return anything as it's calling for FILEHOST and HOST that I'm assuming are globals you've setup. However when I test the url that you put the test video you're using (http://techslides.com/demos/sample-videos/small.mp4) it errors on iOS because it's not HTTPS. Unrelated, but just an FYI.

Are you developing for Android or Apple? Can you show me your package.json file as well?

I notice that you're importing some custom components that you made yourself. If you remove these components do you still encounter issues? Are you exporting them as the default component within their own files? What I mean is that in the Login, Loading and ExpertExam components do you have the following:

```js
export default class Login {}

// or 

class Login {}

export default Login;

// instead of 

export class Login {}
// etc.
```

If not you'll need to add curly brackets around your import statements or add the default keyword:

```js
import {Login} from './Login';
```

**Comment by kylemilloy** [comment]
Any luck?

**Comment by CoderSwitch** [comment]
Thank you for your help and serious solution. I am iOS development. I will try your answer and reply to you later.

**Comment by CoderSwitch** [comment]
I tried the solution you said, but it still doesn't work.

**Comment by CoderSwitch** [comment]
[package.json.zip](https://github.com/itsnubix/react-native-video-controls/files/1886898/package.json.zip)

**Comment by kylemilloy** [comment]
Ahhh...you're using RN version <45...hmmm...lemme look into it some more here...

**Comment by kylemilloy** [comment]
Alright...I think I know what's up...this is a guess however as I am unable to test back previous versions of react-native so I'll have to rely on you testing this for me.

So you're likely using v1.5.1 of `react-native-video-controls` which includes a change to how background images were used starting in react-native v46+. That said, you're using react-native v44 alpha release which doesn't have this update so you're likely encountering the error. (you can see this update [here](https://github.com/itsnubix/react-native-video-controls/commit/5f41a370a2d0ab3e74e13d306b2aff4a7cdafecc))

So the root problem is my documentation sucks...I'm advising people to use v.1.x for RN <46 and that's just not right. They should be using v.1.3 or lower. I've updated the packages documentation to reflect this.

So to fix your problem let's try updating your package.json. If you could, downgrade react-native-video to ^1.0.0 and react-native-video-controls to ^1.3.0

**Comment by CoderSwitch** [comment]
According to your solution successfully run, thank you very much for your help, because this project is relatively old, also not developed by themselves, I am still a novice, so I am at a loss, really thank you for your help, thank you again

**Comment by CoderSwitch** [comment]
You can turn it off when you check my reply, or I'll shut it down tomorrow. Thank you again for your help and careful answers.

**Comment by kylemilloy** [comment]
Glad it worked. :)
