### ISSUE TITLE
"ref" doesn't point to the underlying react-native-video instance

### ISSUE THREAD

**Issue by fabdrol** [itsnubix/react-native-video-controls#92]
**Context:** I need to access the reference to the `react-native-video` instance in order to execute functions like `this.videoPlayer.seek(...)`. 

**Expected behaviour:** `this.videoPlayer` references an instance of `react-native-video` and provides access to instance methods such as `seek()`. 

**Actual, buggy behaviour:** `this.videoPlayer` references an instance of `react-native-video-controls` (I think?) and provides *no access* to instance methods such as `seek()`. 

**Edit:** I *can* access the underlying player, but it's unintuitive and not documented. Using the code below the ref is availalbe on: `this.videoPlayer.player.ref`

**Code:**
```
<VideoPlayer
          ref={ref => { this.videoPlayer = ref }}
          source={{ uri: Array.isArray(this.props.uri) ? this.props.uri[this.state.activeStream] : this.props.uri }}
          rate={1.0}
          volume={0}
          paused={false}
          resizeMode='contain'
          style={styles.player}
          onProgress={data => this.setState({ currentTime: data.currentTime })}
          onBack={() => { this.props.closeVideoPlayer() }}
          controls
          repeat
          muted
        />
```

**Comment by kylemilloy** [comment]
The video component is likely loaded onto the player key in videoPlayer...

Like so:
```js
// ...
ref={ref => this.videoPlayer = ref}
// ...

this.videoPlayer.player.ref // <- the reference to the actual <Video> component.
```

You can see this get set on Line 1108 of VideoPlayer.js.

Alternatively, see here for how I call the reference and use seek...
https://github.com/itsnubix/react-native-video-controls/issues/87

**Comment by kylemilloy** [comment]
PS - great bug report. 👍

**Comment by kylemilloy** [comment]
I agree with you on this...It wouldn't hurt to add some documentation for how to access these lower level functions but I don't think I'll document how to access the `<Video>` component directly as there is some state management that's going on that shouldn't be side stepped. Obviously you can grab the ref from player.ref (soon to be player._ref, I think) if you insist, but I don't wanna make it easy for people...

I'll need to clean up some of the code and relabel some things...in hindsight there are props and methods that are private that shouldn't be and public stuff that shouldn't be...need to standardize the verbiage I wanna use as well...

**Comment by fabdrol** [comment]
@kylemilloy that makes sense, I've closed the issue. Useful for people in the future, though! 

P.s.: thanks for getting back so fast, and great work on the component.

**Comment by kylemilloy** [comment]
No problem and thank you!

I'm going to reopen this one as a reminder to myself to tidy things up and write some documentation for those functions...

**Comment by laurent22** [comment]
Having access to `seek()` is quite important. Perhaps it should be added directly to the react-native-video-controls component - it would do the additional state management if needed and then call Video.seek.

**Comment by kylemilloy** [comment]
Going to address this in v3...stay tuned.

**Comment by Atuldhaka** [comment]
Need to access the seek function, as video player do not get back to the initial position after full video is played. need to reset the position of the progress bar.

**Comment by lucasfp-br** [comment]
> Need to access the seek function, as video player do not get back to the initial position after full video is played. need to reset the position of the progress bar.

You can set a player ref in your component and use the 'seekTo' method:

`
<VideoPlayer
    ref={playerRef} // if using class component, ref={(ref) => { this.playerRef = ref; }}
    onEnd={() => playerRef.current.seekTo(0)} // if using class component, playerRef.seekTo(0) maybe works
    [...]
/>`
