### ISSUE TITLE
calculateVolumePositionFromVolume error

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [itsnubix/react-native-video-controls#93]
Hi
I don't think `calculateVolumePositionFromVolume()` is working correctly: 

`
calculateVolumePositionFromVolume() {
        return this.player.volumeWidth / this.state.volume;
    }
`

If `volumeWidth` is 150 and `volume` is a number between 0 and 1, then I think the division should be replaced with a multiplication.

Amirite?

**Comment by kylemilloy** [comment]
Heh. Good catch. No denying your logic...lemme spin up a quick test when I get into the office and try init'ing the component with 0.1 volume to see how it positions it.

**Comment by jenskuhrjorgensen** [comment]
Btw, I also experienced some problems with not being able to mute the sound via the volume bar because of the addition of `this.player.iconOffset` in setVolumePosition. I removed that and changed a few other styles to make it work to my needs :) 
Great lib though - saved me a bunch of time! 👍

**Comment by Yorden** [comment]
@kylemilloy will this change be in the latest release?  I can confirm myself that setting this initial value does change the volume placement.

**Comment by kylemilloy** [comment]
It will be though I haven't had the time to patch it yet.

**Comment by jenskuhrjorgensen** [comment]
This has been fixed in [this merge PR](https://github.com/itsnubix/react-native-video-controls/commit/d1c7821b576a899d0bf53550eec9394efd916777).

This can be closed.
