### ISSUE TITLE
issues when seeking to a video time that hasn't loaded yet

### ISSUE THREAD

**Issue by ryndshn** [itsnubix/react-native-video-controls#94]
hello!

i've noticed that when seeking to a section of the video that hasn't loaded yet, the loading animation does not show and the video will also jump backwards. 

in my specific case, i will attempt to seek to 400 seconds, but instead, it jumps back to around 394 seconds; i've tested several other examples, and it works similarly. whenever i attempt to seek to a time in the video that is significantly further ahead from where it's currently playing from, it does this. i seek by exposing the seekTo() function in `VideoPlayer.js`. i have a feeling the jumping backwards thing is due to how react-native-video works, and not a problem with react-native-video-controls. however, i thought i would mention it because it may be something worth accounting for in this library. the problem occurs with an HLS stream, specifically, a `.m3u8` file. this video has two resolutions and is segmented every 10 seconds. 

when debugging, i can see that there is one onProgress call that has the correct currentTime (the one i seekTo), but then the next call has the incorrect one (occurs after load). 

what i think is happening: i think it begins loading those segments when it sees you want to start playing from that position. it then begins playing from the beginning of the closest segment. because 400 seconds may occur in the middle of a segment, it begins playing from the beginning, which would be a time before it. 

if there are more details needed, let me know.

**Comment by kylemilloy** [comment]
Thanks...been busy here so haven't had a chance to look into this but am spending some cycles today and tomorrow going through some of these open tickets.

**Comment by kylemilloy** [comment]
Where does the time go...

I think you're right...it's a matter of loading at the beginning of a segment vs. loading where you drop the seeker handle. Not sure how we'd begin to fix this but likely an issue with the underlying `react-native-video` package. I would advise if you're still experiencing issues to follow the [Apple Encoding spec](https://developer.apple.com/library/archive/technotes/tn2224/_index.html/). Off the top of my head, they recommend 6s segments and keyframes (I-Frames) every 2s. 

I'll leave this open for now until a time where I can find a better solution.
