### ISSUE TITLE
Local Video Can't Play in android

### ISSUE THREAD

**Issue by rishaChoubey** [itsnubix/react-native-video-controls#97]
Hello,

I need a help that by using the below syntax, we are unable to play video in android device

<VideoPlayer source={require('./resourses/abc.mp4')}
          navigator={this.props.navigator}

          controlTimeout={15000}         // hide controls after ms of inactivity.
          navigator={navigator}          // prop from React Native <Navigator> component
          seekColor={'#FFF'}             // fill/handle colour of the seekbar
          videoStyle={{}}                // Style appended to <Video> component
          style={{}}                     // Style appended to <View> container

          // event callbacks
          onError={() => { }}                     // Fired when an error is encountered on load
          onBack={() => { this.backAction() }}     // Function fired when back button is pressed.
          onEnd={() => { this.backActionEnd() }}      // Fired when the video is complete.

          // disabling individual controls
          disableFullscreen={false}      // Used to hide the Fullscreen control.
          disableSeekbar={false}         // Used to hide the Seekbar control.
          disableVolume={true}          // Used to hide the Volume control.
          disableBack={false}            // Used to hide the Back control.
          disableTimer={true}
        />

Can anyone please help on the same?

**Comment by csto** [comment]
I've noticed that react-native-video does not work in a simulator.  Did you try it on an actual device?

**Comment by rishaChoubey** [comment]
yes tried but still it is not working.

**Comment by kylemilloy** [comment]
Does it work with other sources?
