### ISSUE TITLE
setState still called when component is unmounted

### ISSUE THREAD

**Issue by pieter888** [itsnubix/react-native-video-controls#98]
Issue: 
When VideoPlayer is unmounted, the `_hideControls()` function is still called due to a `setTimeout` for hiding the controls. This causes a "Can't call setState (or forceUpdate) on an unmounted component" warning.

Suggested fix:
Change `_hideControls()` to only call `setState()` if component is mounted. Use `componentDidMount` and `componentWillUnmount` to keep track of this.

Note:
I've noticed `clearControlTimeout()` but it doens't seem to fire properly, even if I try to call it myself, the method is still called after some time. The suggested fix does solve the problem for me.

**Comment by kylemilloy** [comment]
merged.
